### PR TITLE
Fix client key permissions

### LINKED ISSUE #4193: 'C:/Users/USERNAME/AppData/Local/multipass-client-certificate/multipass_cert_key.pem': Permission denied(13)
FYI this error occurred (every time) when installing Multipass 1.16.0 RC (v1.16.0-rc3) on a clean Windows 11 Pro:

```
C:\Users\USERNAME>multipass version
[error] [client] Caught an unhandled exception: failed to open file 'C:/Users/USERNAME/AppData/Local/multipass-client-certificate/multipass_cert_key.pem': Permission denied(13)
```

FYI the error did _not_ occur when installing Multipass 1.16.0 RC (v1.16.0-rc3) on top of (a prior install) of Multipass 1.15.1

### PR DESCRIPTION
**Pull request by Sploder12**
There was a change in logic in when permissions are set for ssl certificates which caused newly created client certificates to have overly restrictive permissions. This fixes that.

Also there was a bug where unix permissions weren't converted to Windows permissions correctly. This fixes that.

Setting the permissions of the file to read by everyone does not change security since the parent folder maintains the user only access. However, in the future it would be nice to give read permissions directly to the user instead of everyone.

closes #4193

### CODE REVIEW

**Comment by ricab** [comment]
How come this affected only Windows? Or was that not so?

**Comment by Sploder12** [comment]
> How come this affected only Windows? Or was that not so?

I never checked if it affected the other platforms, I wouldn't be surprised if it did

**Review by ricab — CHANGES_REQUESTED** [review]
I tried this and it worked fine on a pristine install on Windows, but read-by-all private key?

**Comment by Sploder12** [comment]
> I tried this and it worked fine on a pristine install on Windows, but read-by-all private key?

Yep, unfortunately that's how it was and as far as I know how it needs to be without a big change in the clients.

**Comment by holta** [comment]
> I tried this and it worked fine on a pristine install on Windows, but read-by-all private key?

The failure was repeated for me: hypothetically (might) also relate to residue left over from 1.15.1 and/or 1.16 RC?

**Comment by Sploder12** [comment]
> The failure was repeated for me: hypothetically (might) also relate to residue left over from 1.15.1 and/or 1.16 RC?

This fix doesn't affect existing files so residue from 1.16 RC would still cause this error

**Comment by xmkg** [comment]
> There was a change in logic in when permissions are set for ssl certificates which caused newly created client certificates to have overly restrictive permissions. This fixes that.
> 
> Setting the permissions of the file to read by everyone does not change security since the parent folder maintains the user only access. However, in the future it would be nice to give read permissions directly to the user instead of everyone.
> 
> closes #4193

@Sploder12 thanks for the fix!

If I understand it correctly, we're basically falling back to the parent folder's permissions, right? The user who installed the multipass would naturally have the proper permissions to the parent folder;  therefore, they can access the file, but not the others.

**Comment by Sploder12** [comment]
> If I understand it correctly, we're basically falling back to the parent folder's permissions, right? The user who installed the multipass would naturally have the proper permissions to the parent folder; therefore, they can access the file, but not the others.

Yep!

File: src/platform/platform_win.cpp [hunk 1]
```diff
@@ -460,7 +460,7 @@ DWORD set_specific_perms(LPSTR path, WELL_KNOWN_SID_TYPE sid_type, DWORD access_
 
 DWORD convert_permissions(int unix_perms)
 {
-    if (unix_perms & 07)
+    if (unix_perms == 07)
```
Comment (ricab) [inline src/platform/platform_win.cpp:463]: Why does this need to receive an int, rather than the original perms? All of `set_permissions` should be able to use constants therein, rather than magic numbers, no? Anyway, something for another time.

**Review by ricab — APPROVED** [review]
Alright, I've verified this on Linux and Windows and all looks good now. Permissions on the root certificate, private keys, and client certificates all look correct now. 

image

image

**Comment by ricab** [comment]
@xmkg I am going ahead and merging this, to speed things up, but if you could still review it after the fact (either here or in a new RC), I'd appreciate it. Thanks!
