### PR TITLE
[linux] increase image resizing timeout to 5 minutes (Fixes #1187)

### LINKED ISSUE #1187: image resize timeout too low
With the new Raspberry Pi 4 running Ubuntu 19.10 Eoan Ermine that has KVM enabled, I am still unable to run multipass containers:

```
$ multipass launch bionic
launch failed: failed to start qemu instance
```

```
$ sudo snap logs -n=all multipass
2019-11-19T15:45:09Z systemd[1]: Started Service for snap application multipass.multipassd.
2019-11-19T15:45:12Z multipassd[2315]: Unable to determine subnet for the mpqemubr0 subnet
2019-11-19T15:45:12Z dnsmasq[2466]: started, version 2.75 cachesize 150
2019-11-19T15:45:12Z dnsmasq[2466]: compile time options: IPv6 GNU-getopt DBus i18n IDN DHCP DHCPv6 no-Lua TFTP conntrack ipset auth DNSSEC loop-detect inotify
2019-11-19T15:45:12Z dnsmasq-dhcp[2466]: DHCP, IP range 10.162.62.2 -- 10.162.62.254, lease time infinite
2019-11-19T15:45:12Z dnsmasq-dhcp[2466]: DHCP, sockets bound exclusively to interface mpqemubr0
2019-11-19T15:45:12Z dnsmasq[2466]: using local addresses only for domain multipass
2019-11-19T15:45:12Z dnsmasq[2466]: reading /etc/resolv.conf
2019-11-19T15:45:12Z dnsmasq[2466]: using local addresses only for domain multipass
2019-11-19T15:45:12Z dnsmasq[2466]: using nameserver 127.0.0.53#53
2019-11-19T15:45:12Z dnsmasq[2466]: read /etc/hosts - 7 addresses
2019-11-19T15:45:12Z dnsmasq[2466]: cannot read /var/snap/multipass/common/data/multipassd/network/dnsmasq.hosts: No such file or directory
2019-11-19T15:45:13Z multipassd[2315]: gRPC listening on unix:/run/multipass_socket, SSL:on
2019-11-19T15:45:13Z multipassd[2315]: QIODevice::write (QFile, "/var/snap/multipass/common/cache/multipassd/vault/multipassd-image-records.json"): device not open
2019-11-19T16:22:22Z dnsmasq[2466]: reading /etc/resolv.conf
2019-11-19T16:22:22Z dnsmasq[2466]: using local addresses only for domain multipass
2019-11-19T16:22:22Z dnsmasq[2466]: using nameserver 127.0.0.53#53
2019-11-19T16:22:22Z multipassd[2315]: process working dir '/snap/multipass/1231/qemu'
2019-11-19T16:22:22Z dnsmasq[2466]: reading /etc/resolv.conf
2019-11-19T16:22:22Z multipassd[2315]: process program 'qemu-system-aarch64'
2019-11-19T16:22:22Z dnsmasq[2466]: using local addresses only for domain multipass
2019-11-19T16:22:22Z multipassd[2315]: process arguments '--enable-kvm, -hda, /var/snap/multipass/common/data/multipassd/vault/instances/snapcraft-edgexfoundry/ubuntu-18.04-minimal-cloudimg-amd64.img, -smp, 2, -m, 2048M, -device, virtio-net-pci,netdev=hostnet0,id=net0,mac=52:54:00:52:a1:e4, -netdev, tap,id=hostnet0,ifname=tap-5600b8eb87b,script=no,downscript=no, -qmp, stdio, -cpu, host, -chardev, null,id=char0, -serial, chardev:char0, -nographic, -cdrom, /var/snap/multipass/common/data/multipassd/vault/instances/snapcraft-edgexfoundry/cloud-init-config.iso'
2019-11-19T16:22:22Z dnsmasq[2466]: using nameserver 127.0.0.53#53
2019-11-19T16:22:23Z multipassd[2315]: process error occurred FailedToStart
2019-11-19T16:22:23Z multipassd[2315]: attempting to release non-existant addr: 52:54:00:52:a1:e4
2019-11-19T16:22:23Z dnsmasq[2466]: reading /etc/resolv.conf
2019-11-19T16:22:23Z dnsmasq[2466]: using local addresses only for domain multipass
2019-11-19T16:22:23Z dnsmasq[2466]: using nameserver 127.0.0.53#53
2019-11-19T16:22:23Z dnsmasq[2466]: reading /etc/resolv.conf
2019-11-19T16:22:23Z dnsmasq[2466]: using local addresses only for domain multipass
2019-11-19T16:22:23Z dnsmasq[2466]: using nameserver 127.0.0.53#53
2019-11-19T16:36:00Z dnsmasq[2466]: reading /etc/resolv.conf
2019-11-19T16:36:00Z dnsmasq[2466]: using local addresses only for domain multipass
2019-11-19T16:36:00Z dnsmasq[2466]: using nameserver 127.0.0.53#53
2019-11-19T16:36:00Z dnsmasq[2466]: reading /etc/resolv.conf
2019-11-19T16:36:00Z dnsmasq[2466]: using local addresses only for domain multipass
2019-11-19T16:36:00Z dnsmasq[2466]: using nameserver 127.0.0.53#53
2019-11-19T16:36:00Z dnsmasq[2466]: reading /etc/resolv.conf
2019-11-19T16:36:00Z dnsmasq[2466]: using local addresses only for domain multipass
2019-11-19T16:36:00Z dnsmasq[2466]: using nameserver 127.0.0.53#53
2019-11-19T17:16:49Z multipassd[2315]: Process operation timed out
2019-11-19T17:16:51Z multipassd[2315]: QProcess: Destroyed while process ("qemu-img") is still running.
2019-11-19T17:16:51Z dnsmasq[2466]: reading /etc/resolv.conf
2019-11-19T17:16:51Z dnsmasq[2466]: using local addresses only for domain multipass
2019-11-19T17:16:51Z dnsmasq[2466]: using nameserver 127.0.0.53#53
2019-11-19T17:16:51Z multipassd[2315]: process working dir '/snap/multipass/1231/qemu'
2019-11-19T17:16:51Z multipassd[2315]: process program 'qemu-system-aarch64'
2019-11-19T17:16:51Z multipassd[2315]: process arguments '--enable-kvm, -hda, /var/snap/multipass/common/data/multipassd/vault/instances/consistent-martin/ubuntu-18.04-server-cloudimg-arm64.img, -smp, 1, -m, 1024M, -device, virtio-net-pci,netdev=hostnet0,id=net0,mac=52:54:00:4b:2c:07, -netdev, tap,id=hostnet0,ifname=tap-5a9b6083db1,script=no,downscript=no, -qmp, stdio, -cpu, host, -chardev, null,id=char0, -serial, chardev:char0, -nographic, -cdrom, /var/snap/multipass/common/data/multipassd/vault/instances/consistent-martin/cloud-init-config.iso'
2019-11-19T17:16:52Z dnsmasq[2466]: reading /etc/resolv.conf
2019-11-19T17:16:52Z dnsmasq[2466]: using local addresses only for domain multipass
2019-11-19T17:16:52Z dnsmasq[2466]: using nameserver 127.0.0.53#53
2019-11-19T17:16:52Z dnsmasq[2466]: reading /etc/resolv.conf
2019-11-19T17:16:52Z dnsmasq[2466]: using local addresses only for domain multipass
2019-11-19T17:16:52Z dnsmasq[2466]: using nameserver 127.0.0.53#53
2019-11-19T17:16:52Z multipassd[2315]: process error occurred FailedToStart
2019-11-19T17:16:52Z multipassd[2315]: attempting to release non-existant addr: 52:54:00:4b:2c:07
2019-11-19T17:16:52Z dnsmasq[2466]: reading /etc/resolv.conf
2019-11-19T17:16:52Z dnsmasq[2466]: using local addresses only for domain multipass
2019-11-19T17:16:52Z dnsmasq[2466]: using nameserver 127.0.0.53#53
2019-11-19T17:16:52Z dnsmasq[2466]: reading /etc/resolv.conf
2019-11-19T17:16:52Z dnsmasq[2466]: using local addresses only for domain multipass
2019-11-19T17:16:52Z dnsmasq[2466]: using nameserver 127.0.0.53#53
```

system info:
```
$ kvm-ok
INFO: /dev/kvm exists
KVM acceleration can be used
$ cat /boot/config-$(uname -r) | grep KVM
CONFIG_HAVE_KVM_IRQCHIP=y
CONFIG_HAVE_KVM_IRQFD=y
CONFIG_HAVE_KVM_IRQ_ROUTING=y
CONFIG_HAVE_KVM_EVENTFD=y
CONFIG_KVM_MMIO=y
CONFIG_HAVE_KVM_MSI=y
CONFIG_HAVE_KVM_CPU_RELAX_INTERCEPT=y
CONFIG_KVM_VFIO=y
CONFIG_HAVE_KVM_ARCH_TLB_FLUSH_ALL=y
CONFIG_KVM_GENERIC_DIRTYLOG_READ_PROTECT=y
CONFIG_HAVE_KVM_IRQ_BYPASS=y
CONFIG_HAVE_KVM_VCPU_RUN_PID_CHANGE=y
CONFIG_KVM=y
CONFIG_KVM_ARM_HOST=y
CONFIG_KVM_ARM_PMU=y
CONFIG_KVM_INDIRECT_VECTORS=y
$ uname -a
Linux ubuntu 5.3.0-1012-raspi2 #14-Ubuntu SMP Mon Nov 11 10:06:55 UTC 2019 aarch64 aarch64 aarch64 GNU/Linux
$ snap list multipass --all
Name       Version  Rev   Tracking  Publisher   Notes
multipass  0.8.1    1231  beta      canonical✓  classic
$ snap version
snap    2.42.1
snapd   2.42.1
series  16
ubuntu  19.10
kernel  5.3.0-1012-raspi2
```

(note that this issue originally happened in https://github.com/CanonicalLtd/multipass/issues/770, but that was modified to just be about unsupported kvm, but now kvm is supported on rpi4 arm64 with https://bugs.launchpad.net/ubuntu/+source/linux-raspi2/+bug/1783961 resolved in the most recent kernel update)

### PR DESCRIPTION
**Pull request by Saviq**

### CODE REVIEW

File: tests/linux/test_backend_utils.cpp [hunk 1]
```diff
@@ -67,8 +67,8 @@ void simulate_qemuimg_info(const mpt::MockProcess* process, const QString& expec
         ON_CALL(*process, read_all_standard_error).WillByDefault(Return(produce_output));
 }
 
-void simulate_qemuimg_resize(const mpt::MockProcess* process, const QString& expect_img,
-                             const mp::MemorySize& expect_size, const mp::ProcessState& produce_result)
+void simulate_qemuimg_resize(mpt::MockProcess* process, const QString& expect_img, const mp::MemorySize& expect_size,
```
Comment (ricab) [inline tests/linux/test_backend_utils.cpp:70]: Intriguing that this worked before. I suppose actions go outside of the mock...

File: tests/linux/test_backend_utils.cpp [hunk 2]
```diff
@@ -80,7 +80,7 @@ void simulate_qemuimg_resize(const mpt::MockProcess* process, const QString& exp
     EXPECT_THAT(args.at(2),
                 ResultOf([](const auto& val) { return mp::MemorySize{val.toStdString()}; }, Eq(expect_size)));
 
-    EXPECT_CALL(*process, execute).WillOnce(Return(produce_result));
+    EXPECT_CALL(*process, execute(300000)).Times(1).WillOnce(Return(produce_result));
```
Comment (ricab) [inline tests/linux/test_backend_utils.cpp:83]: I wonder if this is a bit too specific. Do we really want to check the exact timeout? If so, it should probably be an imported constant. But I think this could just check `execute(_)`.

**Comment by ricab** [comment]
Oh just noticed you'd requested another review.

File: tests/linux/test_backend_utils.cpp (hunk 1 above)
Comment (Saviq) [reply tests/linux/test_backend_utils.cpp:70]: Yup.

File: tests/linux/test_backend_utils.cpp (hunk 2 above)
Comment (Saviq) [reply tests/linux/test_backend_utils.cpp]: Made this into a `mp::backend::image_resize_timeout` constant. We're likely to turn this into a setting at some point.

**Comment by Saviq** [comment]
> Oh just noticed you'd requested another review.

Yours would be more than enough ;)

File: src/platform/backends/shared/linux/backend_utils.h [hunk 3]
```diff
@@ -29,6 +30,10 @@ class ProcessFactory;
 
 namespace backend
 {
+using namespace std::chrono_literals;
+
+constexpr auto image_resize_timeout = std::chrono::duration_cast<std::chrono::milliseconds>(5min).count();
```
Comment (ricab) [inline src/platform/backends/shared/linux/backend_utils.h:35]: Nice :)

Comment (ricab) [reply src/platform/backends/shared/linux/backend_utils.h:35]: Just one thing: `const` missing (it's unintuitive, but not implied by constexpr). Something I have forgotten a few times myself (we should probably have a PR just to fix that everywhere).

Comment (ricab) [reply src/platform/backends/shared/linux/backend_utils.h:35]: Forgot I could just do it here...

```suggestion
constexpr const auto image_resize_timeout = std::chrono::duration_cast<std::chrono::milliseconds>(5min).count();
```

Comment (ricab) [reply src/platform/backends/shared/linux/backend_utils.h:35]: Wrong, as discused in IRC
