### PR TITLE
[sftp] open local files in binary mode

### LINKED ISSUE #2990: Transferring non-plaintext files in or out of the virtual machine corrupts the files
**Describe the bug**
When I transfer in or out non-plaintext files in or out of my instance, the file is unreadable on the receiving OS.
I have tried reconfiguring a new instance and the same issue occurs, I have also asked colleagues to try this on different systems and they experience the same behaviour.

**To Reproduce**
How, and what happened?
1. `multipass transfer primary:/home/ubuntu/foo.zip .`
2. Unable to open the zip file in host operating system
3. `multipass transfer .\bar.zip primary:/home/ubuntu/bar.zip`
4. Unable to open zip file (readable in Windows) on guest operating system
In both examples, the zip file has been valid and readable on the source OS before transfer.

**Expected behavior**
In previous versions I have been able to successfully transfer files in and out of my guest operating system.

**Logs**
Please provide logs from the daemon, see [accessing logs](https://multipass.run/docs/accessing-logs) on where to find them on your platform.

**Additional info**
 - OS: Microsoft Windows 10 and 11
- ```
  multipass --version 
  multipass   1.11.1+win
  multipassd  1.11.1+win#
- ```
  multipass info --all
  Name:           primary
  State:          Running
  IPv4:           172.31.189.71
  Release:        Ubuntu 22.04.2 LTS
  Image hash:     dc5b5a43c267 (Ubuntu 22.04 LTS)
  CPU(s):         2
  Load:           1.02 1.07 1.08
  Disk usage:     22.7GiB out of 24.0GiB
  Memory usage:   1.5GiB out of 15.6GiB
  Mounts:         --
- ```
  multipass get local. Driver
  hyperv

**Additional context**
It is possible to transfer files in and out of the guest operating system using secure copy.

### PR DESCRIPTION
**Pull request by andrei-toterman**
The SFTP client opened files in text mode, which made the transfer of binary files on Windows fail. This PR makes the SFTP client open files in binary mode.

fix #2990

### CODE REVIEW

File: src/utils/file_ops.cpp [hunk 1]
```diff
@@ -144,14 +144,14 @@ void mp::FileOps::open(std::fstream& stream, const char* filename, std::ios_base
     stream.open(filename, mode);
 }
 
-std::unique_ptr<std::ostream> mp::FileOps::open_write(const fs::path& path) const
+std::unique_ptr<std::ostream> mp::FileOps::open_write(const fs::path& path, std::ios_base::openmode mode) const
```
Comment (luis4a0) [inline src/utils/file_ops.cpp:147]: Shouldn't this have a default open mode?

File: src/utils/file_ops.cpp [hunk 2]
```diff
@@ -144,14 +144,14 @@ void mp::FileOps::open(std::fstream& stream, const char* filename, std::ios_base
...
 {
-    return std::make_unique<std::ofstream>(path);
+    return std::make_unique<std::ofstream>(path, mode);
 }
 
-std::unique_ptr<std::istream> mp::FileOps::open_read(const fs::path& path) const
+std::unique_ptr<std::istream> mp::FileOps::open_read(const fs::path& path, std::ios_base::openmode mode) const
```
Comment (luis4a0) [inline src/utils/file_ops.cpp:152]: Same as above here.

**Review by luis4a0 — COMMENTED** [review]
Hey @andrei-toterman, thanks for this! Looks great, two minor comments in the code and we are ready to go.

File: src/utils/file_ops.cpp (hunk 1 above)
Comment (andrei-toterman) [reply src/utils/file_ops.cpp:147]: There are default open modes defined in the header file :smile:

**Review by luis4a0 — APPROVED** [review]
Good to go!

**Comment by luis4a0** [comment]
bors retry

**Comment by andrei-toterman** [comment]
bors retry

**Comment by townsend2010** [comment]
The Mac are runners are quite busy...let's try again.

bors retry

**Comment by luis4a0** [comment]
One more chance before merging manually: bors retry

**Comment by luis4a0** [comment]
bors retry

**Comment by townsend2010** [comment]
The integration tests had a problem and a reboot of the host fixed it.  The subsequent integration test run passed: https://github.com/canonical/multipass/actions/runs/4554356362/jobs/8032237181

I'm just going to merge manually.

bors cancel
