### PR TITLE
[lxd] check for suspend support before attempting operation

### LINKED ISSUE #3322: [lxd] multipass stops sshfs mount on suspend even when suspend isn't supported
**Describe the bug**
The LXD backend driver does not support suspending instances. However, if the instance has mounts they will be stopped on calling suspend even though the instance cannot be suspended. You then need to restart the instance to get them back.

**To Reproduce**
1. `multipass set local.driver=lxd`
2. `multipass mount ...`
3. `multipass suspend ...`

### PR DESCRIPTION
**Pull request by sharder996**
Fixes #3322

### CODE REVIEW

File: src/platform/backends/lxd/lxd_virtual_machine_factory.h [hunk 1]
```diff
@@ -63,4 +63,9 @@ class LXDVirtualMachineFactory : public BaseVirtualMachineFactory
 };
 } // namespace multipass
 
+inline void multipass::LXDVirtualMachineFactory::require_suspend_support() const
+{
+    throw NotImplementedOnThisBackendException{"snapshots"};
```
Comment (townsend2010) [inline src/platform/backends/lxd/lxd_virtual_machine_factory.h:68]: `suspend`

File: src/platform/backends/lxd/lxd_virtual_machine_factory.h [hunk 2]
```diff
@@ -63,4 +63,9 @@ class LXDVirtualMachineFactory : public BaseVirtualMachineFactory
 };
 } // namespace multipass
 
+inline void multipass::LXDVirtualMachineFactory::require_suspend_support() const
```
Comment (townsend2010) [inline src/platform/backends/lxd/lxd_virtual_machine_factory.h:66]: You should be able to write a unit test that catches that an exception is thrown here.

File: src/platform/backends/shared/base_virtual_machine_factory.h [hunk 3]
```diff
@@ -109,4 +111,8 @@ inline void multipass::BaseVirtualMachineFactory::require_snapshots_support() co
     throw NotImplementedOnThisBackendException{"snapshots"};
 }
 
+inline void multipass::BaseVirtualMachineFactory::require_suspend_support() const
```
Comment (townsend2010) [inline src/platform/backends/shared/base_virtual_machine_factory.h:114]: Also, it should be pretty straight forward to write a unit test for this and show that it doesn't throw an exception.

**Review by townsend2010 — CHANGES_REQUESTED** [review]
Hey @sharder996,

Thanks for this.  A few comments below that need addressing.

File: src/daemon/daemon.cpp [hunk 4]
```diff
@@ -2199,6 +2199,7 @@ try // clang-format on
 
     if (status.ok())
     {
+        config->factory->require_suspend_support();
```
Comment (townsend2010) [inline src/daemon/daemon.cpp:2202]: I think with the `TestDaemonSuspend` that you created, you could probably actually get coverage for this.  You could create another test in there that "overrides" the `mock_factory` and instead use an actual `LXDVirtualMachineFactory` and check that it fails.

File: tests/test_daemon_suspend.cpp [hunk 5]
```diff
@@ -0,0 +1,126 @@
...
+    mp::SuspendRequest request;
+    request.mutable_instance_names()->add_instance_name(mock_instance_name);
+
+    auto status = call_daemon_slot(daemon,
+                                   &mp::Daemon::suspend,
+                                   request,
+                                   StrictMock<mpt::MockServerReaderWriter<mp::SuspendReply, mp::SuspendRequest>>{});
+
+    EXPECT_TRUE(status.ok());
+}
```
Comment (townsend2010) [inline tests/test_daemon_suspend.cpp:126]: Seems there is no newline here?

**Review by townsend2010 — COMMENTED** [review]
Hey @sharder996!

I made a couple of comments below.  See if you can add that last test to get 100% coverage here:)

File: src/daemon/daemon.cpp (hunk 4 above)
Comment (townsend2010) [reply src/daemon/daemon.cpp:2202]: Ok, so Codecov does not count mocked calls in it's coverage.  That said, the following *might* work since it's not a mock and is a stub instead:
```diff
--- a/tests/stub_virtual_machine_factory.h
+++ b/tests/stub_virtual_machine_factory.h
@@ -90,6 +90,11 @@ struct StubVirtualMachineFactory : public multipass::BaseVirtualMachineFactory
         return std::make_unique<StubVMImageVault>();
     }
 
+    void require_suspend_support() const override
+    {
+        throw NotImplementedOnThisBackendException{"suspend"};
+    }
+
     std::unique_ptr<TempDir> tmp_dir;
 };
 }
diff --git a/tests/test_daemon_suspend.cpp b/tests/test_daemon_suspend.cpp
index c1ccac39d..45e98f482 100644
--- a/tests/test_daemon_suspend.cpp
+++ b/tests/test_daemon_suspend.cpp
@@ -41,12 +41,8 @@ struct TestDaemonSuspend : public mpt::DaemonTestFixture
         EXPECT_CALL(mock_settings, unregister_handler).Times(AnyNumber());
 
         config_builder.vault = std::make_unique<NiceMock<mpt::MockVMImageVault>>();
-
-        mock_factory = use_a_mock_vm_factory();
     }
 
-    mpt::MockVirtualMachineFactory* mock_factory;
-
     const std::string mock_instance_name{"real-zebraphant"};
     const std::string mac_addr{"52:54:00:73:76:28"};
     const std::string fake_target_path{"/home/ubuntu/foo"};
@@ -63,6 +59,7 @@ struct TestDaemonSuspend : public mpt::DaemonTestFixture
 
 TEST_F(TestDaemonSuspend, suspendNotSupportedDoesNotStopMounts)
 {
+    auto mock_factory = use_a_mock_vm_factory();
     std::unordered_map<std::string, mp::VMMount> mounts{
         {fake_target_path, {"foo", {}, {}, mp::VMMount::MountType::Native}}};
 
@@ -96,6 +93,7 @@ TEST_F(TestDaemonSuspend, suspendNotSupportedDoesNotStopMounts)
 
 TEST_F(TestDaemonSuspend, suspendStopsMounts)
 {
+    auto mock_factory = use_a_mock_vm_factory();
     std::unordered_map<std::string, mp::VMMount> mounts{
         {fake_target_path, {"foo", {}, {}, mp::VMMount::MountType::Native}}};
 
@@ -123,4 +121,23 @@ TEST_F(TestDaemonSuspend, suspendStopsMounts)
                                    StrictMock<mpt::MockServerReaderWriter<mp::SuspendReply, mp::SuspendRequest>>{});
 
     EXPECT_TRUE(status.ok());
}
+
+TEST_F(TestDaemonSuspend, suspendNotSupportedReturnsErrorStatus)
+{
+    const auto [temp_dir, filename] = plant_instance_json(fake_json_contents(mac_addr, extra_interfaces));
+    config_builder.data_directory = temp_dir->path();
+
+    mp::Daemon daemon{config_builder.build()};
+
+    mp::SuspendRequest request;
+    request.mutable_instance_names()->add_instance_name(mock_instance_name);
+
+    auto status = call_daemon_slot(daemon,
+                                   &mp::Daemon::suspend,
+                                   request,
+                                   StrictMock<mpt::MockServerReaderWriter<mp::SuspendReply, mp::SuspendRequest>>{});
+
+    EXPECT_EQ(status.error_code(), grpc::StatusCode::FAILED_PRECONDITION);
+    EXPECT_THAT(status.error_message(), HasSubstr(("The suspend feature is not implemented on this backend.")));
+}
```

**Comment by townsend2010** [comment]
Hey @sharder996, this needs rebased and any conflicts fixed.  Thanks!

**Review by townsend2010 — APPROVED** [review]
Hey @sharder996!

LGTM :+1:  Thanks!
