### PR TITLE
Pull disk info from home partition

### LINKED ISSUE #3041: `info` not working on core22 instances
```
$ mp launch core22
Launched: fresh-python
$ mp info fresh-python
[2023-04-14T19:05:47.474] [error] [client] Caught an unhandled exception:  755761152
  26464256
3159937024 is not a valid memory size - need a non-negative integer (in base 10) or a decimal followed by K, M, or G (e.g. 1234B, 42MiB, 0.5G)
```

**Logs**

```
abr 14 19:07:55 ricab-XPS-9320 multipassd[26716]: Executing 'cat /proc/loadavg | cut -d ' ' -f1-3'
abr 14 19:07:55 ricab-XPS-9320 multipassd[26716]: /root/parts/multipass/src/src/ssh/ssh_process.cpp:118 read_stream(type = 0, timeout = -1):
abr 14 19:07:55 ricab-XPS-9320 multipassd[26716]: /root/parts/multipass/src/src/ssh/ssh_process.cpp:136 read_stream(): num_bytes = 15
abr 14 19:07:55 ricab-XPS-9320 multipassd[26716]: /root/parts/multipass/src/src/ssh/ssh_process.cpp:136 read_stream(): num_bytes = 0
abr 14 19:07:55 ricab-XPS-9320 multipassd[26716]: Executing 'free -b | grep 'Mem:' | awk '{printf $3}''
abr 14 19:07:55 ricab-XPS-9320 multipassd[26716]: /root/parts/multipass/src/src/ssh/ssh_process.cpp:118 read_stream(type = 0, timeout = -1):
abr 14 19:07:55 ricab-XPS-9320 multipassd[26716]: /root/parts/multipass/src/src/ssh/ssh_process.cpp:136 read_stream(): num_bytes = 9
abr 14 19:07:55 ricab-XPS-9320 multipassd[26716]: /root/parts/multipass/src/src/ssh/ssh_process.cpp:136 read_stream(): num_bytes = 0
abr 14 19:07:55 ricab-XPS-9320 multipassd[26716]: Executing 'free -b | grep 'Mem:' | awk '{printf $2}''
abr 14 19:07:55 ricab-XPS-9320 multipassd[26716]: /root/parts/multipass/src/src/ssh/ssh_process.cpp:118 read_stream(type = 0, timeout = -1):
abr 14 19:07:55 ricab-XPS-9320 multipassd[26716]: /root/parts/multipass/src/src/ssh/ssh_process.cpp:136 read_stream(): num_bytes = 10
abr 14 19:07:55 ricab-XPS-9320 multipassd[26716]: /root/parts/multipass/src/src/ssh/ssh_process.cpp:136 read_stream(): num_bytes = 0
abr 14 19:07:55 ricab-XPS-9320 multipassd[26716]: Executing 'df --output=used $(sudo fdisk -l | grep 'Linux filesystem' | awk '{print $1}') -B1 | sed 1d'
abr 14 19:07:55 ricab-XPS-9320 multipassd[26716]: /root/parts/multipass/src/src/ssh/ssh_process.cpp:118 read_stream(type = 0, timeout = -1):
abr 14 19:07:55 ricab-XPS-9320 multipassd[26716]: /root/parts/multipass/src/src/ssh/ssh_process.cpp:136 read_stream(): num_bytes = 30
abr 14 19:07:55 ricab-XPS-9320 multipassd[26716]: /root/parts/multipass/src/src/ssh/ssh_process.cpp:136 read_stream(): num_bytes = 0
abr 14 19:07:55 ricab-XPS-9320 multipassd[26716]: Executing 'df --output=size $(sudo fdisk -l | grep 'Linux filesystem' | awk '{print $1}') -B1 | sed 1d'
abr 14 19:07:55 ricab-XPS-9320 multipassd[26716]: /root/parts/multipass/src/src/ssh/ssh_process.cpp:118 read_stream(type = 0, timeout = -1):
abr 14 19:07:55 ricab-XPS-9320 multipassd[26716]: /root/parts/multipass/src/src/ssh/ssh_process.cpp:136 read_stream(): num_bytes = 33
abr 14 19:07:55 ricab-XPS-9320 multipassd[26716]: /root/parts/multipass/src/src/ssh/ssh_process.cpp:136 read_stream(): num_bytes = 0
abr 14 19:07:55 ricab-XPS-9320 multipassd[26716]: Executing 'nproc'
abr 14 19:07:55 ricab-XPS-9320 multipassd[26716]: /root/parts/multipass/src/src/ssh/ssh_process.cpp:118 read_stream(type = 0, timeout = -1):
abr 14 19:07:55 ricab-XPS-9320 multipassd[26716]: /root/parts/multipass/src/src/ssh/ssh_process.cpp:136 read_stream(): num_bytes = 2
abr 14 19:07:55 ricab-XPS-9320 multipassd[26716]: /root/parts/multipass/src/src/ssh/ssh_process.cpp:136 read_stream(): num_bytes = 0
abr 14 19:07:55 ricab-XPS-9320 multipassd[26716]: Executing 'ip -brief -family inet address show scope global'
abr 14 19:07:55 ricab-XPS-9320 multipassd[26716]: /root/parts/multipass/src/src/ssh/ssh_process.cpp:118 read_stream(type = 0, timeout = -1):
abr 14 19:07:55 ricab-XPS-9320 multipassd[26716]: /root/parts/multipass/src/src/ssh/ssh_process.cpp:136 read_stream(): num_bytes = 61
abr 14 19:07:55 ricab-XPS-9320 multipassd[26716]: /root/parts/multipass/src/src/ssh/ssh_process.cpp:136 read_stream(): num_bytes = 0
abr 14 19:07:55 ricab-XPS-9320 multipassd[26716]: Executing 'cat /etc/os-release | grep 'PRETTY_NAME' | cut -d \" -f2'
abr 14 19:07:55 ricab-XPS-9320 multipassd[26716]: /root/parts/multipass/src/src/ssh/ssh_process.cpp:118 read_stream(type = 0, timeout = -1):
abr 14 19:07:55 ricab-XPS-9320 multipassd[26716]: /root/parts/multipass/src/src/ssh/ssh_process.cpp:136 read_stream(): num_bytes = 15
abr 14 19:07:55 ricab-XPS-9320 multipassd[26716]: /root/parts/multipass/src/src/ssh/ssh_process.cpp:136 read_stream(): num_bytes = 0
```

**Additional info**
 - OS: Ubuntu Jammy
- `multipass version`: I tried this on 1.13.0-dev.437.pr2913+g6ed45ffb, I imagine it's in edge too, maybe the RC (?)
- `multipass get local.driver`: qemu

**Additional context**
I suspect the output of one of those commands is different in core22 and we are not generic enough in parsing.

### PR DESCRIPTION
**Pull request by sharder996**
Since there are sometimes multiple entries that are labeled as Linux Filesystem, edit the command to sort them and take the largest one. This is under the assumption that the main filesystem is the largest.

This command is getting a bit convoluted at this point, so other suggestions on where to get this info is welcome.

Fixes #3041

### CODE REVIEW

File: src/daemon/daemon.cpp [hunk 1]
```diff
@@ -1480,12 +1480,12 @@ try // clang-format on
...
             info->set_memory_usage(mpu::run_in_ssh_session(session, "free -b | grep 'Mem:' | awk '{printf $3}'"));
             info->set_memory_total(mpu::run_in_ssh_session(session, "free -b | grep 'Mem:' | awk '{printf $2}'"));
-            info->set_disk_usage(mpu::run_in_ssh_session(
-                session,
-                "df --output=used $(sudo fdisk -l | grep 'Linux filesystem' | awk '{print $1}') -B1 | sed 1d"));
-            info->set_disk_total(mpu::run_in_ssh_session(
-                session,
-                "df --output=size $(sudo fdisk -l | grep 'Linux filesystem' | awk '{print $1}') -B1 | sed 1d"));
+            info->set_disk_usage(
+                mpu::run_in_ssh_session(session, "df --output=used $(sudo fdisk -l | grep 'Linux filesystem' | awk "
```
Comment (ricab) [inline src/daemon/daemon.cpp:1484]: I never really got all this. Can't we just say `df --output=used /home`? In core instances, that's the partition with free space. In others, it's just under the root partition.

Comment (sharder996) [reply src/daemon/daemon.cpp]: Using `/home` seems to work for ubuntu instances, older and newer core instances, and also appliances. Was able to simplify the original command a bit as well.

File: src/daemon/daemon.cpp [hunk 2]
```diff
@@ -1480,12 +1480,8 @@ try // clang-format on
             info->set_load(mpu::run_in_ssh_session(session, "cat /proc/loadavg | cut -d ' ' -f1-3"));
             info->set_memory_usage(mpu::run_in_ssh_session(session, "free -b | grep 'Mem:' | awk '{printf $3}'"));
             info->set_memory_total(mpu::run_in_ssh_session(session, "free -b | grep 'Mem:' | awk '{printf $2}'"));
-            info->set_disk_usage(mpu::run_in_ssh_session(
-                session,
-                "df --output=used $(sudo fdisk -l | grep 'Linux filesystem' | awk '{print $1}') -B1 | sed 1d"));
-            info->set_disk_total(mpu::run_in_ssh_session(
-                session,
-                "df --output=size $(sudo fdisk -l | grep 'Linux filesystem' | awk '{print $1}') -B1 | sed 1d"));
+            info->set_disk_usage(mpu::run_in_ssh_session(session, "df --output=used /home -B1 | sed 1d"));
```
Comment (ricab) [inline src/daemon/daemon.cpp:1483]:
```suggestion
            // /home is a separate partition in core instances, part of the root partition in others
            info->set_disk_usage(mpu::run_in_ssh_session(session, "df --output=used /home -B1 | sed 1d"));
```

Comment (ricab) [reply src/daemon/daemon.cpp:1483]: ignore please

**Review by ricab — CHANGES_REQUESTED** [review]
Hey @sharder996, sorry I was not thinking straight. This gives us only part of the picture. The total, in particular, can be very far off.

I haven't found a simple way to just get the size and usage of the *disk*, and not partitions therein,  but this should give a better approximation: `df -h --total -T -t ext4 -t vfat` (you can edit as needed, e.g. remove `-T and -h`, add `--output`). That takes the EFI partition into account (`vfat`), along with all `ext4`, regardless of whether they are writable. You can get the total in the last line.

Of course, as soon as there are partitions in other formats, this will break. So not ideal, but better I think. I considered `df /dev/sda*`, but that reports things that appear to be overlayed and so the totals are bigger. Feel free to look around for a better option, but remember core instances have a limited set of tools available (e.g. no `lshw`).

**Comment by sharder996** [comment]
Hey @ricab, thanks for giving some alternate suggestions! Generally I'm fine with your suggestions, but I have a few comments.

If we include other partitions in the reported amounts, there is going to be a discrepancy between `multipass info` and what a user can effectively put in their vm. Seeing as how we've had a few github issues in the past of users bricking their vms because of full disks I have some concerns.

Another thing I noticed when using `-t ext4 -t vfat` is that it is effectively the same as `/dev/sda*/` as all those partitions are of those types.

**Review by ricab — APPROVED** [review]
LGTM, thanks!

bors r+
