### PR TITLE
[test] Improve the MockLogger and adapt tests accordingly

### LINKED ISSUE #1676: MockLogger not reset in some tests
Some tests register a mock logger globally, but fail to reset it. Since the logger's lifetime is managed with a shared_ptr, it will stick around for ensuing tests. Also, call expectations on the mock logger are only verified on the following reset (different test).

Some examples I noticed:
https://github.com/canonical/multipass/blob/834eca128704bd0a149bc8a8852db4912a83f15f/tests/lxd/test_lxd_backend.cpp#L58
https://github.com/canonical/multipass/blob/0d74fa3510e7f57c443cb9a4264fa4a7893b70aa/tests/test_base_virtual_machine_factory.cpp#L51

### PR DESCRIPTION
**Pull request by ricab**
This tries to make the `MockLogger` interface safer and more intuitive. Introduces some functionality that will be needed in upcoming tests, and employs it already where applicable, simplifying setup code.

Fixes #1676.

### CODE REVIEW

File: src/logging/log.cpp [hunk 1]
```diff
@@ -71,3 +71,8 @@ void mpl::set_logger(std::shared_ptr<Logger> logger)
     global_logger = std::move(logger);
     qInstallMessageHandler(qt_message_handler);
 }
+
+auto mpl::get_logger() -> Logger* // for tests, don't rely on it lasting
```
Comment (townsend2010) [inline src/logging/log.cpp:75]: I'm curious why you use the `auto blah -> Logger*` format here instead of just a straight up `Logger* blah` like in the function definition?  I know they are treated one and the same and I'm not going to block this at all, but I'm just wondering if there is some sort of optimization I don't know about :smile:

File: tests/mock_logger.cpp [hunk 2]
```diff
@@ -0,0 +1,57 @@
...
+namespace mp = multipass;
+namespace mpl = multipass::logging;
+namespace mpt = multipass::test;
+using namespace testing;
+
+mpt::MockLogger::MockLogger(const PrivatePass&)
+{
+}
+
+auto mpt::MockLogger::inject() -> Scope
```
Comment (townsend2010) [inline tests/mock_logger.cpp:29]: Same question as above...

File: src/logging/log.cpp (hunk 1 above)
Comment (ricab) [reply src/logging/log.cpp:75]: It's just that the trailing return type is automatically looked up in the function's scope (like arguments). So you can say `auto ns::f() -> foo` whereas the namespace is needed if `foo` comes first: `ns::foo ns::f()`. It feels like a little redundancy that can be economized, so I usually do it like that. When the ns is small it may be more typing because of the added auto.

File: tests/mock_logger.cpp (hunk 2 above)
Comment (ricab) [reply tests/mock_logger.cpp:29]: The advantage is clearer here, the alternative would be: `mpt:MockLogger::Scope mpt::MockLogger::inject()`.

**Comment by ricab** [comment]
Thanks for the review and for fixing conflicts @townsend2010! Let me know if there's anything else you need from my side.

File: src/logging/log.cpp (hunk 1 above)
Comment (townsend2010) [reply src/logging/log.cpp:75]: Ah, cool, yeah, that certainly makes it easier to code for without sacrificing readability.

File: tests/mock_logger.cpp (hunk 2 above)
Comment (townsend2010) [reply tests/mock_logger.cpp:29]: Yep, I see.  Nice!

**Comment by townsend2010** [comment]
Good to go!  Thanks!

bors merge
