### PR TITLE
Make core 20/22 not change IP address over reboot

### LINKED ISSUE #2690: Multipass fails to notice IP change over reboot
```plain
$ multipass launch http://cdimage.ubuntu.com/ubuntu-core/20/stable/current/ubuntu-core-20-amd64.img.xz
launch failed: The following errors occurred:
timed out waiting for initialization to complete

$ multipass ls
Name                    State             IPv4             Image
fluttering-jackal       Restarting        --               Not Available

$ multipass stop fluttering-jackal

$ multipass start fluttering-jackal

$ multipass ls
Name                    State             IPv4             Image
fluttering-jackal       Running           10.127.143.204   Not Available

$ multipass exec fluttering-jackal grep PRETTY /etc/os-release
PRETTY_NAME="Ubuntu Core 20"
```

The problem is that the machine changes client-id over reboots, so DNSMasq gives up a new IP and Multipass fails to notice:
```plain
$ journalctl -u snap.multipass.multipassd.service --since -1h |grep DHCPACK
sie 01 15:27:08 michal-laptop dnsmasq-dhcp[10199]: DHCPACK(mpqemubr0) 10.127.143.203 52:54:00:59:fc:d9 ubuntu
sie 01 15:28:20 michal-laptop dnsmasq-dhcp[10199]: DHCPACK(mpqemubr0) 10.127.143.204 52:54:00:59:fc:d9 fluttering-jackal
sie 01 15:32:55 michal-laptop dnsmasq-dhcp[10199]: DHCPACK(mpqemubr0) 10.127.143.204 52:54:00:59:fc:d9 fluttering-jackal
sie 01 15:34:57 michal-laptop dnsmasq-dhcp[10199]: DHCPACK(mpqemubr0) 10.127.143.204 52:54:00:59:fc:d9 fluttering-jackal
```

### PR DESCRIPTION
**Pull request by andrei-toterman**
This PR makes it so that when a Linux QEMU instance reboots, it checks the `dnsmasq.leases` file for leases that have the same MAC address as the instance but under a different host name and releases them. This is needed for core20 and core22, which change host names during launching and get the daemon confused about which IP is the correct one.

It also makes sure that when an instance is done rebooting, it has a `Running` state, since those instances were getting stuck in a `Restarting` state.

fix #2690

### CODE REVIEW

**Review by luis4a0 — APPROVED** [review]
Hey @andrei-toterman, thanks! Code looks good and it indeed works. As for the coverage, I can say although this reduces a bit the total coverage, the uncovered code changed was uncovered before. So I'm OK with that.

**Comment by luis4a0** [comment]
bors r+

:crossed_fingers:

**Review by townsend2010 — COMMENTED** [review]
This looks like the new `dnsmasq` option **doesn't** work with version we use in the snap: https://github.com/canonical/multipass/runs/8043246718?check_suite_focus=true#step:3:1346

CI FTW!!!

**Review by townsend2010 — CHANGES_REQUESTED** [review]
Yep, confirmed the `--dhcp-ignore-clid` option is not supported by `dnsmasq` we include in the snap.

**Comment by luis4a0** [comment]
> Yep, confirmed the `--dhcp-ignore-clid` option is not supported by `dnsmasq` we include in the snap.

Hey @townsend2010! Sorry, this escaped my sight. What can we do, then?

The options I see are:
1. build with `core22`, we'll have there a new version of the deb package
2. make a `dnsmasq` snap and make our snap depend on it
3. build `dnsmasq` from source

What do you think?

**Comment by townsend2010** [comment]
Hey @luis4a0 and @andrei-toterman,

> build with `core22`, we'll have there a new version of the deb package

I would like to move to `core22`, but that is really risky at this point in the cycle.  That in and off itself is a Roadmap item and should be done early in the cycle, so I say no at this point.

> make a `dnsmasq` snap and make our snap depend on it

Calling executables in one snap from another snap in this manner is not really supported by design.  Caveat: It is possible in some scenarios to do this either via portals or via dbus/desktop files mechanism, but that is a bunch of heavy lifting for this and something I will avoid.

>     build `dnsmasq` from source

Of these 3 options, this is the most likely to happen, but it's still quite a bit of heavy lifting for something we could drop when we move to the `core22` base, but it certainly something could be done within this cycle and still get this in.

@andrei-toterman, I believe you had another solution working before using this cleaner solution before, correct?  If so, I think it may be better to just use your original solution with a `FIXME:` to change to this solution once we move to the `core22` base.

**Comment by andrei-toterman** [comment]
@townsend2010 Sure, I'll update the PR with the old fix :smile:

File: src/platform/backends/qemu/linux/qemu_platform_detail_linux.cpp [hunk 1]
```diff
@@ -187,6 +188,15 @@ QStringList mp::QemuPlatformDetail::vm_platform_args(const VirtualMachineDescrip
                                             tap_device_name, vm_desc.default_mac_address));
 }
 
+// FIXME: after moving to core22, this will be handled by dnsmasq --dhcp-ignore-clid
+void multipass::QemuPlatformDetail::release_mac_with_different_hostname(const std::string& hw_addr,
+                                                                        const std::string& name)
+{
+    if (auto ip_and_host = dnsmasq_server->get_ip_and_host_for(hw_addr);
+        ip_and_host.has_value() && ip_and_host.value().second != name)
+        dnsmasq_server->release_mac(hw_addr);
```
Comment (luis4a0) [inline src/platform/backends/qemu/linux/qemu_platform_detail_linux.cpp:197]: I know this is very picky, but I couldn't understand this at first sight because of the unfortunate indentation. What about:
```
    if (auto ip_and_host = dnsmasq_server->get_ip_and_host_for(hw_addr); ip_and_host && ip_and_host->second != name)
        dnsmasq_server->release_mac(hw_addr);
```
?

The whole `if` block would fit in one line. It is completely valid to test the `std::optional` for nullity and the `operator*` is equivalent to `value()` when the optional contains a value.

**Review by luis4a0 — APPROVED** [review]
Hey @andrei-toterman, now it works :P

**Comment by luis4a0** [comment]
bors cancel

**Comment by luis4a0** [comment]
Sorry @andrei-toterman, I approved instead of waiting for you to answer. Just those two details and we'll be done.

File: tests/qemu/linux/test_qemu_platform_detail.cpp [hunk 2]
```diff
@@ -209,3 +211,19 @@ TEST_F(QemuPlatformDetail, writing_ipforward_file_failure_logs_expected_message)
...
+        .WillOnce(Return(std::make_optional(std::make_pair(ip_address, name))))
+        .WillOnce(Return(std::make_optional(std::make_pair(ip_address, name + "not"))))
+        .WillOnce(Return(std::nullopt));
+    EXPECT_CALL(*mock_dnsmasq_server, release_mac(hw_addr));
+
+    mp::QemuPlatformDetail qemu_platform_detail{data_dir.path()};
+    qemu_platform_detail.release_mac_with_different_hostname(hw_addr, name);
+    qemu_platform_detail.release_mac_with_different_hostname(hw_addr, name);
+    qemu_platform_detail.release_mac_with_different_hostname(hw_addr + "not", name);
+}
```
[the remark this answers is not in the document]
Comment (andrei-toterman) [reply tests/qemu/linux/test_qemu_platform_detail.cpp:229]: Oops, yup, I'll add it!

File: src/platform/backends/qemu/linux/qemu_platform_detail_linux.cpp (hunk 1 above)
Comment (andrei-toterman) [reply src/platform/backends/qemu/linux/qemu_platform_detail_linux.cpp:197]: Indeed it is not very readable. Thanks for the tips!

**Comment by luis4a0** [comment]
Thanks @andrei-toterman! Let's give it a try!

bors r+
