### PR TITLE
[sftpserver] Removing reverse mapping handling when creating symlink

### LINKED ISSUE #2407: Symlinks broken over mounts
```plain
$ multipass start
$ multipass exec primary -- ln -s Home/foo Home/bar
ln: failed to create symbolic link 'Home/bar': Input/output error
$ ls -l
...
lrwxrwxrwx  1 root   root      8 Jan 24 19:05 bar -> Home/foo
```

```plain
[2022-01-24T19:56:00.480] [error] [sshfs-mounts] There was an error with sshfs_server for instance "primary" with path 'Home': Crashed - program: /Library/Application Support/com.canonical.multipass/bin/sshfs_server; error: Process crashed
[2022-01-24T19:56:00.480] [warning] [sshfs-mounts] Mount 'Home' in instance "primary" has stopped unexpectedly: program: /Library/Application Support/com.canonical.multipass/bin/sshfs_server; error: Process crashed
```

### PR DESCRIPTION
**Pull request by townsend2010**
Fixes #2407

### CODE REVIEW

File: src/sshfs_mount/sftp_server.cpp [hunk 1]
```diff
@@ -1000,19 +1000,6 @@ int mp::SftpServer::handle_symlink(sftp_client_message msg)
...
-    auto new_uid = reverse_uid_for(msg->attr->uid, current_dir.ownerId());
-    auto new_gid = reverse_gid_for(msg->attr->gid, current_dir.groupId());
-
-    if (MP_PLATFORM.chown(new_name, new_uid, new_gid) < 0)
-    {
-        mpl::log(mpl::Level::trace, category,
-                 fmt::format("failed to chown '{}' to owner:{} and group:{}", new_name, new_uid, new_gid));
-        return reply_failure(msg);
-    }
-
```
Comment (luis4a0) [inline src/sshfs_mount/sftp_server.cpp:1015]: Yeah, this was the culprit.

**Review by luis4a0 — COMMENTED** [review]
Hey @townsend2010, thanks for this! Don't you think we need to add a test for making sure that symlinks are _not_ mapped?

**Comment by luis4a0** [comment]
Following our discussion, there is nothing to test. So
bors r+
