### PR TITLE
clarify behavior of `multipass shell` in short_help and description

### LINKED ISSUE #1133: `multipass shell` launching a VM is unexpected
I just typed `multipass shell` and accidentally hit Return before typing my instance name in, and was very surprised to see multipass launch a new VM. This was particularly confusing given that the short help says "Open a shell on a _running_ instance" (emphasis mine, of course), so that's what I assumed it did.

Once I'd seen this happen, I looked at the full help text, and I think we also have some confusing wording there. Specifically, "If the instance is not running, an attempt is made to start it" is inaccurate, as `multipass` did not attempt to `start` it, it instead `launch`ed a completely new VM.

### PR DESCRIPTION
**Pull request by levkropp**
close #1133

### CODE REVIEW

**Comment by ricab** [comment]
Hi @giuliazanchi, how does this change look to you?

File: src/client/cli/cmd/shell.cpp [hunk 1]
```diff
@@ -117,12 +117,12 @@ std::vector<std::string> cmd::Shell::aliases() const
 
 QString cmd::Shell::short_help() const
 {
-    return QStringLiteral("Open a shell on a running instance");
+    return QStringLiteral("Open a shell on the primary or specified instance");
```
Comment (giuliazanchi) [inline src/client/cli/cmd/shell.cpp:120]: I'd simplify the short help further by just saying: 
```suggestion
    return QStringLiteral("Open a shell on an instance");
```

File: src/client/cli/cmd/shell.cpp [hunk 2]
```diff
@@ -117,12 +117,12 @@ std::vector<std::string> cmd::Shell::aliases() const
...
 }
 
 QString cmd::Shell::description() const
 {
-    return QStringLiteral("Open a shell prompt on the instance.");
+    return QStringLiteral("Open a shell prompt on the instance. If the instance is not running, it will automatically be started.");
```
Comment (giuliazanchi) [inline src/client/cli/cmd/shell.cpp:125]: Good idea to mention this! Just a minor rephrasing suggestion:

```suggestion
    return QStringLiteral("Open a shell prompt on the instance. If the instance is not running, it will be started automatically.");
```

**Review by giuliazanchi — DISMISSED** [review]

**Review by ricab — APPROVED** [review]
Looks good @levkropp, thanks!
