### PR TITLE
Fix root certificate not found when using external directory

### LINKED ISSUE #4246: Certificates inaccessible when MULTIPASS_STORAGE is set
**Describe the bug**

When I do the "multipass list" command or any other command, I get this error:

`
[error] [client] Caught an unhandled exception: failed to open file '/var/snap/multipass/common/data/multipassd/certificates/multipass_root_cert.pem': No such file or directory(2)
`

**To Reproduce**
1. `multipass list`
2. `multipass help`
3. all commands with multipass ...

**Expected behavior**
List vms, create, etc.

**Logs**
Result of `journalctl --unit 'snap.multipass*'` (see logs.txt file)

Other command : `sudo systemctl status snap.multipass.multipassd.service`

```
● snap.multipass.multipassd.service - Service for snap application multipass.multipassd
     Loaded: loaded (/etc/systemd/system/snap.multipass.multipassd.service; enabled; preset: enabled)
    Drop-In: /etc/systemd/system/snap.multipass.multipassd.service.d
             └─override.conf
     Active: active (running) since Sun 2025-07-13 16:24:38 CEST; 54min ago
   Main PID: 16984 (multipassd)
      Tasks: 15 (limit: 76964)
     Memory: 102.7M (peak: 127.1M)
        CPU: 2.130s
     CGroup: /system.slice/snap.multipass.multipassd.service
             ├─16984 /snap/multipass/15214/bin/multipassd --verbosity debug --logger platform
             └─17040 /snap/multipass/15214/usr/sbin/dnsmasq --keep-in-foreground --strict-order --bind-interfaces --pid-file --domain=multipass --local=/multipass/ --except-interface=lo --interface=mpqemubr0 --listen-address=10.234.182>

juil. 13 16:24:38 soso multipassd[16984]: [17112] started: qemu-img snapshot -l /media/soso/7afba588-caba-4b11-879d-783fb3310e311/multipass/data/vault/instances/myminikube/ubuntu-24.04-server-cloudimg-amd64.img
juil. 13 16:24:38 soso multipassd[16984]: Applied AppArmor policy: multipass.qemu-img
juil. 13 16:24:38 soso multipassd[16984]: [17119] started: qemu-img snapshot -l /media/soso/7afba588-caba-4b11-879d-783fb3310e311/multipass/data/vault/instances/mydocker/ubuntu-24.04-server-cloudimg-amd64.img
juil. 13 16:24:38 soso multipassd[16984]: Applied AppArmor policy: multipass.qemu-img
juil. 13 16:24:38 soso multipassd[16984]: [17134] started: qemu-img snapshot -l /media/soso/7afba588-caba-4b11-879d-783fb3310e311/multipass/data/vault/instances/awscli/ubuntu-24.04-server-cloudimg-amd64.img
juil. 13 16:24:38 soso multipassd[16984]: Starting Multipass 1.16.0
juil. 13 16:24:38 soso multipassd[16984]: Daemon arguments: /snap/multipass/15214/bin/multipassd --verbosity debug --logger platform
juil. 13 16:39:39 soso multipassd[16984]: fetch manifest periodically
juil. 13 16:54:40 soso multipassd[16984]: fetch manifest periodically
juil. 13 17:09:41 soso multipassd[16984]: fetch manifest periodically
```

**Additional info**

[logs.txt](https://github.com/user-attachments/files/21205032/logs.txt)

multipass 1.16 with qemu driver
 
Operating System: Kubuntu 24.04
KDE Plasma Version: 5.27.12
KDE Frameworks Version: 5.115.0
Qt Version: 5.15.13
Kernel Version: 6.11.0-29-generic (64-bit)
Graphics Platform: X11
Processors: 6 × Intel® Core™ i5-9600K CPU @ 3.70GHz
Memory: 62.7 Gio of RAM
Graphics Processor: AMD Radeon RX 6650 XT

**Additional context**
I changed the storage to an external SSD, it always worked except today with this bug. Here is the content of the file (`/etc/systemd/system/snap.multipass.multipassd.service.d/override.conf`) :

```
[Service]
Environment=MULTIPASS_STORAGE=/media/soso/7afba588-caba-4b11-879d-783fb3310e311/multipass
```

All of my instances are in this path : `/media/soso/7afba588-caba-4b11-879d-783fb3310e311/multipass/data/vault/instances` or json file (`cat multipassd-instance-image-records.json`) :

```
{
    "awscli": {
        "image": {
            "aliases": [
            ],
            "current_release": "",
            "id": "8d6161defd323d24d66f85dda40e64e2b9021aefa4ca879dcbc4ec775ad1bbc5",
            "original_release": "24.04 LTS",
            "path": "/media/soso/7afba588-caba-4b11-879d-783fb3310e311/multipass/data/vault/instances/awscli/ubuntu-24.04-server-cloudimg-amd64.img",
            "release_date": "20250516"
        },
        "last_accessed": 1748934853464350208,
        "query": {
            "persistent": false,
            "query_type": 0,
            "release": "noble",
            "remote_name": ""
        }
    },
    "mydocker": {
        "image": {
            "aliases": [
            ],
            "current_release": "",
            "id": "8d6161defd323d24d66f85dda40e64e2b9021aefa4ca879dcbc4ec775ad1bbc5",
            "original_release": "24.04 LTS",
            "path": "/media/soso/7afba588-caba-4b11-879d-783fb3310e311/multipass/data/vault/instances/mydocker/ubuntu-24.04-server-cloudimg-amd64.img",
            "release_date": "20250516"
        },
        "last_accessed": 1749544203538533888,
        "query": {
            "persistent": false,
            "query_type": 0,
            "release": "default",
            "remote_name": ""
        }
    },
    "myminikube": {
        "image": {
            "aliases": [
            ],
            "current_release": "",
            "id": "92d2c4591af9a82785464bede56022c49d4be27bde1bdcf4a9fccc62425cda43",
            "original_release": "24.04 LTS",
            "path": "/media/soso/7afba588-caba-4b11-879d-783fb3310e311/multipass/data/vault/instances/myminikube/ubuntu-24.04-server-cloudimg-amd64.img",
            "release_date": "20250610"
        },
        "last_accessed": 1751309757236737024,
        "query": {
            "persistent": false,
            "query_type": 0,
            "release": "noble",
            "remote_name": ""
        }
    },
    "mywazuh": {
        "image": {
            "aliases": [
            ],
            "current_release": "",
            "id": "92d2c4591af9a82785464bede56022c49d4be27bde1bdcf4a9fccc62425cda43",
            "original_release": "24.04 LTS",
            "path": "/media/soso/7afba588-caba-4b11-879d-783fb3310e311/multipass/data/vault/instances/mywazuh/ubuntu-24.04-server-cloudimg-amd64.img",
            "release_date": "20250610"
        },
        "last_accessed": 1751309757236737024,
        "query": {
            "persistent": false,
            "query_type": 0,
            "release": "noble",
            "remote_name": ""
        }
    }
}
```

And certificates :

```
root@soso:/media/soso/7afba588-caba-4b11-879d-783fb3310e311/multipass/data/certificates# ls -la
total 24
drwx--x--x 2 root root 4096 juil. 13 17:33 .
drwx------ 8 root root 4096 juil. 13 16:24 ..
-rwx------ 1 root root  241 juil. 11 08:24 localhost_key.pem
-rwx------ 1 root root  704 juil. 11 08:24 localhost.pem
-rwx------ 1 root root  241 juil. 11 08:24 localhost_root_key.pem
-rwxr--r-- 1 root root  688 juil. 13 17:33 multipass_root_cert.pem
```

### PR DESCRIPTION
**Pull request by Sploder12**
Changes the logic of where root certificates are stored on all platforms to always be in the same location. This avoids having the client and daemon looking in different locations.

fixes #4246 
MULTI-2104

### CODE REVIEW

File: src/platform/platform_linux.cpp [hunk 1]
```diff
@@ -189,14 +189,6 @@ std::string get_alias_script_path(const std::string& alias)
 
     return aliases_folder.absoluteFilePath(QString::fromStdString(alias)).toStdString();
 }
-
-std::filesystem::path multipass_final_storage_location()
-{
-    const auto user_specified_mp_storage = MP_PLATFORM.multipass_storage_location();
-    const auto mp_final_storage = user_specified_mp_storage.isEmpty() ? mp::utils::snap_common_dir()
```
Comment (sharder996) [inline src/platform/platform_linux.cpp:196]: So, why was this always looking in the snap directory even if `MP_PLATFORM.multipass_storage_location` was set?

Comment (Sploder12) [reply src/platform/platform_linux.cpp:196]: The issue is that it wasn't set on the client but was on the daemon. The client would look in the normal directory while the daemon makes sure it exists in the external directory

**Comment by ricab** [comment]
Copying here to avoid forgetting, the variables that I see for testing are: host OS, local build vs pkg, external storage vs not, fresh or new install.

**Comment by ricab** [comment]
@xmkg, would you be up for a secondary review on this one?

**Review by sharder996 — CHANGES_REQUESTED** [review]
Assuming a user is coming from a broken installation of 1.16.1 with `MULTIPASS_STORAGE` defined and having previously removed the original Multipass snap data directory (i.e. `/var/snap/multipass/data/multipassd` and `/var/snap/multipass/common/cache/multipassd`), I get the follow error:

```
list failed: The user is not authenticated with the Multipass service.
```

I see a new `multipass_root_cert.pem` file being created. Was this file or another certificate created by the daemon process resulting in mismatching certs?

**Comment by Sploder12** [comment]
> I see a new `multipass_root_cert.pem` file being created. Was this file or another certificate created by the daemon process resulting in mismatching certs?

Yep the daemon created it resulting in mismatching certs. I rebased onto #4226 to fix this

File: src/utils/standard_paths.cpp [hunk 2]
```diff
@@ -40,3 +42,22 @@ QString mp::StandardPaths::writableLocation(StandardLocation type) const
...
     return QStandardPaths::writableLocation(type);
 }
+
+std::filesystem::path mp::get_default_daemon_path()
+{
+    using Path = std::filesystem::path;
+    const auto base_dir =
+        utils::in_multipass_snap()
+            ? Path{utils::snap_common_dir().toStdString()} / "data"
+            : Path{MP_STDPATHS.writableLocation(StandardPaths::GenericDataLocation)
```
Comment (xmkg) [inline src/utils/standard_paths.cpp]: This would return ~/.local/share, and ~ would resolve to `/root` and `/home/<user>` depending on the authorization level (root vs regular user).

Comment (xmkg) [reply src/utils/standard_paths.cpp]: @Sploder12 I think this explains why I'm getting the following error:

The daemon and the client are now looking at different paths:

```
./build/bin/multipass list
[error] [client] Caught an unhandled exception: failed to open file '/home/mkg/.local/share/multipassd/certificates/multipass_root_cert.pem': No such file or directory(2)
```
```
[2025-07-22T19:15:15.382] [debug] [ssl-cert-provider] Certificates for the gRPC server (root: /root/.local/share/multipassd/certificates/multipass_root_cert.pem, subordinate: /root/.local/share/multipassd/certificates/localhost.pem) are valid X.509 files
[2025-07-22T19:15:15.382] [warning] [ssl-cert-provider] Existing root certificate (`/root/.local/share/multipassd/certificates/multipass_root_cert.pem`) is not the signer of the gRPC server certificate (`/root/.local/share/multipassd/certificates/localhost.pem`)
```

Comment (xmkg) [reply src/utils/standard_paths.cpp]: The client can connect to the gRPC server with `sudo`:

sudo ./build/bin/multipass list
[sudo] password for mkg: 
list failed: The user is not authenticated with the Multipass service.

Please authenticate before proceeding (e.g. via 'multipass authenticate'). Note that you first need an authenticated user to set and provide you with a trusted passphrase (e.g. via 'multipass set local.passphrase').

File: src/platform/platform_linux.cpp [hunk 3]
```diff
@@ -471,11 +463,12 @@ std::string multipass::platform::host_version()
...
 {
-    constexpr auto* root_cert_file_name = "multipass_root_cert.pem";
-    return mp::utils::in_multipass_snap()
-               ? multipass_final_storage_location() / "data" / daemon_name / "certificates" /
-                     root_cert_file_name
-               : std::filesystem::path{"/usr/local/share/ca-certificates"} / root_cert_file_name;
+    using Path = std::filesystem::path;
+    const auto base_dir = utils::in_multipass_snap()
+                              ? Path{utils::snap_common_dir().toStdString()} / "data"
+                              : Path{"/home/root/.local/share"};
```
Comment (xmkg) [inline src/platform/platform_linux.cpp]: /home/root ?

File: src/platform/platform_win.cpp [hunk 4]
```diff
@@ -1064,7 +1054,9 @@ long long mp::platform::Platform::get_total_ram() const
     return status.ullTotalPhys;
 }
 
-std::filesystem::path mp::platform::Platform::get_root_cert_path() const
+std::filesystem::path mp::platform::Platform::get_root_cert_dir() const
 {
-    return multipass_final_storage_location() / "data" / "certificates" / "multipass_root_cert.pem";
+    // C:\ProgramData is stable and user agnostic
+    static const std::filesystem::path base_dir = "C:\\ProgramData";
```
Comment (xmkg) [inline src/platform/platform_win.cpp]: Drive label C:/ is not guaranteed. Perhaps we can use a Windows API function for it?

File: src/platform/platform_linux.cpp (hunk 3 above)
Comment (xmkg) [reply src/platform/platform_linux.cpp]: Also, I wonder if the client user would be able to access the /root/.local/share

Comment (Sploder12) [reply src/platform/platform_linux.cpp]: haha whoops, although that's probably why I didn't have permission issues...
But yeah, I don't think the client should (or would) be able to access `/root/.local/share`

File: src/platform/platform_win.cpp (hunk 4 above)
Comment (Sploder12) [reply src/platform/platform_win.cpp]: Using `CSIDL_COMMON_APPDATA` since ["This folder is used for application data that is not user specific"](https://learn.microsoft.com/en-us/windows/win32/shell/csidl) and isn't overly restrictive so it fits our needs. It isn't guaranteed to be `ProgramData` but the other guarantees are more important

File: src/platform/platform_linux.cpp (hunk 3 above)
Comment (Sploder12) [reply src/platform/platform_linux.cpp]: moved to /usr/local/etc

File: src/platform/platform_win.cpp [hunk 5]
```diff
@@ -347,6 +348,17 @@ QString systemprofile_app_data_path()
     return ret;
 }
 
+[[nodiscard]] mp::fs::path get_wellknown_path(int csidl)
+{
+    std::array<TCHAR, MAX_PATH + 1> buf{};
+    if (auto err = SHGetFolderPath(NULL, csidl, NULL, SHGFP_TYPE_CURRENT, buf.data()); err != S_OK)
```
Comment (xmkg) [inline src/platform/platform_win.cpp]: SHGetFolderPath is a deprecated function. Can we use the Known Folder API instead? https://learn.microsoft.com/en-us/windows/win32/shell/knownfolderid

**Review by xmkg — CHANGES_REQUESTED** [review]
Works as expected in both Linux (non-snap build) and Windows. I have a request regarding replacing a deprecated Windows API with a new one.

**Review by xmkg — DISMISSED** [review]
LGTM 👍 Works as expected in Windows, and passes all cli-tests in Linux.

**Review by xmkg — APPROVED** [review]
LGTM :+1: Works fine on Windows, passes the cli-tests in Linux. I've encountered a couple of issues during the test, but I don't think they're related to the changes introduced in this PR, nor the root-cert path bug.
