### PR TITLE
[general] compatibility with macOS's c++17 support

### LINKED ISSUE #1258: Symbol not found trying to run on OSX 10.11.6
Just installed 1.0.0 on OSX 10.11.6.  When I try to run I get the following error:

```
$ multipass
dyld: Symbol not found: __ZNSt19bad_optional_accessD1Ev
  Referenced from: /usr/local/bin/multipass
  Expected in: /usr/lib/libc++.1.dylib
 in /usr/local/bin/multipass
Trace/BPT trap: 5
```

### PR DESCRIPTION
**Pull request by Saviq**
To keep our minimal macOS version lower, we need to work around some limitations of their c++17 support. What we know so far:
- `std::optional::value()` and `::reset()` are not supported
- `std::bad_optional_access` has no d'tor (so we mustn't throw it manually either)
- `std::optional::emplace` non-conformant (returns `void` rather than `T&`)
- `std::scoped_lock` is not supported
- `std::lock_guard` needs to be templated

Fixes #1258

### CODE REVIEW

**Comment by ricab** [comment]
It's also a different lock.

File: tests/test_basic_process.cpp [hunk 1]
```diff
@@ -63,7 +63,7 @@ TEST_F(BasicProcessTest, execute_good_command_with_positive_exit_code)
 
     EXPECT_FALSE(process_state.completed_successfully());
     EXPECT_TRUE(process_state.exit_code);
```
Comment (ricab) [inline tests/test_basic_process.cpp]:
```suggestion
    ASSERT_TRUE(process_state.exit_code);
```

File: tests/test_basic_process.cpp [hunk 2]
```diff
@@ -63,7 +63,7 @@ TEST_F(BasicProcessTest, execute_good_command_with_positive_exit_code)
...
-    EXPECT_EQ(exit_code, process_state.exit_code.value());
+    EXPECT_EQ(exit_code, *process_state.exit_code);
```
Comment (ricab) [inline tests/test_basic_process.cpp]: Undefined behavior without the change above.

File: tests/test_basic_process.cpp [hunk 3]
```diff
@@ -77,7 +77,7 @@ TEST_F(BasicProcessTest, execute_good_command_with_zero_exit_code)
 
     EXPECT_TRUE(process_state.completed_successfully());
     EXPECT_TRUE(process_state.exit_code);
```
Comment (ricab) [inline tests/test_basic_process.cpp]:
```suggestion
    ASSERT_TRUE(process_state.exit_code);
```

File: tests/test_basic_process.cpp [hunk 4]
```diff
@@ -100,7 +100,7 @@ TEST_F(BasicProcessTest, process_state_when_runs_and_stops_ok)
 
     process_state = process.process_state();
     EXPECT_TRUE(process_state.exit_code);
```
Comment (ricab) [inline tests/test_basic_process.cpp]:
```suggestion
    ASSERT_TRUE(process_state.exit_code);
```

File: tests/test_basic_process.cpp [hunk 5]
```diff
@@ -186,7 +186,7 @@ TEST_F(BasicProcessTest, process_state_when_runs_and_stops_immediately)
...
```
Comment (ricab) [inline tests/test_basic_process.cpp]:
```suggestion
    ASSERT_TRUE(process_state.exit_code);
```

**Comment by ricab** [comment]
I put together a [little doc](https://docs.google.com/document/d/1LZI-qM1vTwscIgkDpAfrIU74ymVv8byQBDE3V0BIerA/edit), rather than hijacking this soon-to-be-merged PR for future finds.

**Comment by Saviq** [comment]
bors r=ricab
