### PR TITLE
daemon/find: Account for no valid aliases being found

### LINKED ISSUE #1411: multipass find release FATAL
following: https://discourse.ubuntu.com/t/multipass-find-command/8351

```
$ multipass find release:
[libprotobuf FATAL ../3rd-party/grpc/third_party/protobuf/src/google/protobuf/repeated_field.h:1557] CHECK failed: (index) < (current_size_):
libc++abi.dylib: terminating with uncaught exception of type google::protobuf::FatalException: CHECK failed: (index) < (current_size_):
[1]    91774 abort      multipass find release:
```

### PR DESCRIPTION
**Pull request by townsend2010**
On particular platforms, it's possible that some aliases that are found for a
particular remote are not valid, so the created entry needs to be removed in
this case.

Fixes #1411

### CODE REVIEW

File: src/daemon/daemon.cpp [hunk 1]
```diff
@@ -928,6 +928,13 @@ try // clang-format on
                     alias_entry->set_alias(alias.toStdString());
                 }
 
+                // If no aliases are found, then it's an invalid entry
+                if (entry->aliases_info().empty())
+                {
+                    response.mutable_images_info()->RemoveLast();
+                    continue;
+                }
+
```
Comment (Saviq) [inline src/daemon/daemon.cpp]: Hmm this feels like a workaround, shouldn't we be not getting invalid entries here?

Comment (townsend2010) [reply src/daemon/daemon.cpp]: Above this code in the `for` loop is where the check is for if an alias is supported or not.  If no aliases are found, then as this PR proposes, we should not have an entry for the response.  This whole thing is kind of a hack since we added the whole notion of which aliases are supported and which are not depending on the platform well after how we initially implemented remote image querying.  If we want to move all of the logic to determine that somewhere else, then it will require quite a bit of refactoring which beyond the scope of this PR.  This PR simply fixes a crash on Windows and Mac when issuing `multipass find release:`.

Comment (Saviq) [reply src/daemon/daemon.cpp]: Well, yeah, I just mean in the `for` above, we shouldn't even be adding an entry unless we know it's not going to be empty?

**Comment by Saviq** [comment]
Discussed on IRC, this is the best we can do atm.

bors r+
