### PR TITLE
[qemu] pass --conf-file to dnsmasq (Fixes #1468)

### LINKED ISSUE #1468: `/etc/dnsmasq.conf` is read and fails due to confinement if it exists
**Describe the bug**
Describe what your problem is.

**To Reproduce**
How, and what happened?
1. `reboot`
2. `multipass launch`
3. `multipass shell unbeatable-earwig`
4. `ping google.com`

image

**Expected behavior**
I need internet in VM

**Logs**
Sorry for spanish

```
-- Logs begin at Sat 2020-02-29 03:22:41 -03, end at Fri 2020-04-03 18:45:43 -03. --
abr 02 21:54:47 hydraStation systemd[1]: Started Service for snap application multipass.multipassd.
abr 02 21:54:48 hydraStation multipassd[23638]: Unable to determine subnet for the mpqemubr0 subnet
abr 02 21:54:49 hydraStation multipassd[23638]: Using AppArmor support
abr 02 21:54:49 hydraStation multipassd[23893]: Applying AppArmor policy: multipass.dnsmasq
abr 02 21:54:49 hydraStation multipassd[23638]: 
abr 02 21:54:49 hydraStation dnsmasq[23893]: no se puede leer /etc/dnsmasq.conf: Permiso denegado
abr 02 21:54:49 hydraStation multipassd[23638]: 
                                                dnsmasq: no se puede leer /etc/dnsmasq.conf: Permiso denegado
abr 02 21:54:49 hydraStation dnsmasq[23893]: FALLO al iniciar
abr 02 21:54:49 hydraStation multipassd[23638]: gRPC listening on unix:/var/snap/multipass/common/multipass_socket, SSL:on
abr 02 21:54:49 hydraStation multipassd[23638]: QIODevice::write (QFile, "/var/snap/multipass/common/cache/multipassd/vault/multipassd-image-records.json"): device not open
abr 02 21:58:42 hydraStation multipassd[25172]: Applying AppArmor policy: multipass.dnsmasq
abr 02 21:58:42 hydraStation dnsmasq[25174]: iniciado, versión 2.79 tamaño de caché 150
abr 02 21:58:42 hydraStation dnsmasq[25174]: opciones al compilar: IPv6 GNU-getopt DBus i18n IDN DHCP DHCPv6 no-Lua TFTP conntrack ipset auth DNSSEC loop-detect inotify
abr 02 21:58:42 hydraStation dnsmasq-dhcp[25174]: DHCP, IP range 10.215.78.2 -- 10.215.78.254, lease time infinito
abr 02 21:58:42 hydraStation dnsmasq-dhcp[25174]: DHCP, sockets bound exclusively to interface mpqemubr0
abr 02 21:58:42 hydraStation dnsmasq[25174]: se usan direcciones locales sólo para dominio multipass
abr 02 21:58:42 hydraStation dnsmasq[25174]: leyendo /etc/resolv.conf
abr 02 21:58:42 hydraStation dnsmasq[25174]: se usan direcciones locales sólo para dominio multipass
abr 02 21:58:42 hydraStation dnsmasq[25174]: se usa el servidor 127.0.0.53#53
abr 02 21:58:42 hydraStation dnsmasq[25174]: /etc/hosts leído - 8 direcciones
abr 02 21:58:42 hydraStation dnsmasq[25174]: no se puede leer /var/snap/multipass/common/data/multipassd/network/dnsmasq.hosts: No existe el archivo o el directorio
abr 02 22:04:30 hydraStation multipassd[25527]: Applying AppArmor policy: multipass.qemu-img
abr 02 22:04:31 hydraStation multipassd[25537]: Applying AppArmor policy: multipass.qemu-img
abr 02 22:04:31 hydraStation multipassd[25543]: Applying AppArmor policy: multipass.qemu-img
abr 02 22:04:32 hydraStation multipassd[23638]: process working dir '/snap/multipass/1784/qemu'
abr 02 22:04:32 hydraStation multipassd[23638]: process program 'qemu-system-x86_64'
abr 02 22:04:32 hydraStation multipassd[23638]: process arguments '--enable-kvm, -device, virtio-scsi-pci,id=scsi0, -drive, file=/var/snap/multipass/common/data/multipassd/vault/instances/surpassing-cobia/ubuntu
abr 02 22:04:32 hydraStation multipassd[23638]: qemu-system-x86_64: warning: TCG doesn't support requested feature: CPUID.01H:ECX.vmx [bit 5]
abr 02 22:04:32 hydraStation multipassd[25632]: Applying AppArmor policy: multipass.surpassing-cobia.qemu-system-x86_64
abr 02 22:04:32 hydraStation multipassd[23638]: process started
abr 02 22:04:32 hydraStation multipassd[23638]: QMP: {"QMP": {"version": {"qemu": {"micro": 1, "minor": 11, "major": 2}, "package": "(Debian 1:2.11+dfsg-1ubuntu7.23)"}, "capabilities": []}}
abr 02 22:04:32 hydraStation multipassd[23638]: QMP: {"return": {}}
abr 02 22:04:52 hydraStation multipassd[23638]: QMP: {"timestamp": {"seconds": 1585875892, "microseconds": 843033}, "event": "NIC_RX_FILTER_CHANGED", "data": {"name": "net0", "path": "/machine/peripheral/net0/vi
abr 02 22:04:55 hydraStation dnsmasq-dhcp[25174]: DHCPDISCOVER(mpqemubr0) 52:54:00:27:2b:18
abr 02 22:04:55 hydraStation dnsmasq-dhcp[25174]: DHCPOFFER(mpqemubr0) 10.215.78.16 52:54:00:27:2b:18
abr 02 22:04:55 hydraStation dnsmasq-dhcp[25174]: DHCPDISCOVER(mpqemubr0) 52:54:00:27:2b:18
abr 02 22:04:55 hydraStation dnsmasq-dhcp[25174]: DHCPOFFER(mpqemubr0) 10.215.78.16 52:54:00:27:2b:18
abr 02 22:04:55 hydraStation dnsmasq-dhcp[25174]: DHCPREQUEST(mpqemubr0) 10.215.78.16 52:54:00:27:2b:18
abr 02 22:04:55 hydraStation dnsmasq-dhcp[25174]: DHCPACK(mpqemubr0) 10.215.78.16 52:54:00:27:2b:18 surpassing-cobia
abr 02 22:07:12 hydraStation multipassd[23638]: No mounts to stop for instance "surpassing-cobia"
abr 02 22:07:12 hydraStation multipassd[23638]: QMP: {"return": {}}
abr 02 22:07:12 hydraStation multipassd[23638]: QMP: {"timestamp": {"seconds": 1585876032, "microseconds": 769106}, "event": "POWERDOWN"}
abr 02 22:07:12 hydraStation multipassd[23638]: VM powering down
abr 02 22:07:13 hydraStation multipassd[23638]: QMP: {"timestamp": {"seconds": 1585876033, "microseconds": 337650}, "event": "SHUTDOWN", "data": {"guest": true}}
abr 02 22:07:13 hydraStation multipassd[23638]: VM shut down
abr 02 22:07:13 hydraStation multipassd[23638]: process finished with exit code 0
abr 02 22:07:43 hydraStation multipassd[29227]: Applying AppArmor policy: multipass.qemu-img
abr 02 22:07:43 hydraStation multipassd[29233]: Applying AppArmor policy: multipass.qemu-img
abr 02 22:07:43 hydraStation multipassd[23638]: process working dir '/snap/multipass/1784/qemu'
abr 02 22:07:43 hydraStation multipassd[23638]: process program 'qemu-system-x86_64'
abr 02 22:07:43 hydraStation multipassd[23638]: process arguments '--enable-kvm, -device, virtio-scsi-pci,id=scsi0, -drive, file=/var/snap/multipass/common/data/multipassd/vault/instances/grand-hake/ubuntu-18.04
abr 02 22:07:43 hydraStation multipassd[23638]: qemu-system-x86_64: warning: TCG doesn't support requested feature: CPUID.01H:ECX.vmx [bit 5]
abr 02 22:07:43 hydraStation multipassd[29323]: Applying AppArmor policy: multipass.grand-hake.qemu-system-x86_64
abr 02 22:07:43 hydraStation multipassd[23638]: process started
```

**Additional info**
 - OS: 
```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.4 LTS"
NAME="Ubuntu"
VERSION="18.04.4 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.4 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```
```
Name:           primary
State:          Stopped
IPv4:           --
Release:        --
Image hash:     fe3030939822 (Ubuntu 18.04 LTS)
Load:           --
Disk usage:     --
Memory usage:   --
Mounts:         /home/vay3t => Home
                    UID map: 1000:default
                    GID map: 1000:default

Name:           canny-rattler
State:          Stopped
IPv4:           --
Release:        --
Image hash:     fe3030939822 (Ubuntu 18.04 LTS)
Load:           --
Disk usage:     --
Memory usage:   --

Name:           unbeatable-earwig
State:          Running
IPv4:           10.75.70.118
Release:        Ubuntu 18.04.4 LTS
Image hash:     fe3030939822 (Ubuntu 18.04 LTS)
Load:           0.00 0.02 0.04
Disk usage:     1001.5M out of 4.7G
Memory usage:   77.2M out of 985.1M
```

**Additional context**
My user is in sudo

### PR DESCRIPTION
**Pull request by Saviq**
Otherwise it may try (and fail) to read /etc/dnsmasq.conf, when it exists, and die.

### CODE REVIEW

File: tests/qemu/test_dnsmasq_process_spec.cpp [hunk 1]
```diff
@@ -40,12 +40,12 @@ TEST_F(TestDnsmasqProcessSpec, default_arguments_correct)
...
-        QStringList({"--strict-order", "--bind-interfaces", "--pid-file=/path/to/file.pid", "--domain=multipass",
-                     "--local=/multipass/", "--except-interface=lo", "--interface=bridgey", "--listen-address=1.2.3.1",
-                     "--dhcp-no-override", "--dhcp-authoritative", "--dhcp-leasefile=/data/dnsmasq.leases",
-                     "--dhcp-hostsfile=/data/dnsmasq.hosts", "--dhcp-range", "1.2.3.2,1.2.3.254,infinite"}));
+    EXPECT_EQ(spec.arguments(),
+              QStringList({"--strict-order", "--bind-interfaces", "--pid-file=/path/to/file.pid", "--domain=multipass",
+                           "--local=/multipass/", "--except-interface=lo", "--interface=bridgey",
+                           "--listen-address=1.2.3.1", "--dhcp-no-override", "--dhcp-authoritative",
+                           "--dhcp-leasefile=/data/dnsmasq.leases", "--dhcp-hostsfile=/data/dnsmasq.hosts",
+                           "--dhcp-range", "1.2.3.2,1.2.3.254,infinite", "--conf-file=/data/dnsmasq.conf"}));
```
Comment (Saviq) [inline tests/qemu/test_dnsmasq_process_spec.cpp:48]: Sorry, `clang-format`…

**Comment by Saviq** [comment]
bors cancel

**Comment by Saviq** [comment]
Actually it won't:
```
kwi 06 21:01:45 michal-laptop multipassd[42306]: 
                                                 dnsmasq: cannot read /var/snap/multipass/common/data/multipassd/network/dnsmasq.conf: Nie ma takiego pliku ani katalogu
kwi 06 21:01:45 michal-laptop dnsmasq[42647]: FAILED to start up
```

When there's no `--conf-file`, it will glance over `/etc/dnsmasq.conf` missing, but if you give it a `--conf-file`, it needs to be there…

Will fix tomorrow.

**Comment by Saviq** [comment]
> bors cancel

d'uh.

bors r-

Will undo.
