### PR TITLE
Format dates in image vault and custom image host in c locale

### LINKED ISSUE #2442: Issues with unicode characters in image path
**Describe the bug**
When using the `snapcraft` command to build a snap, I face the following error:
```
Launching a VM.
Build environment is in unknown state, cleaning first.
info failed: The following errors occurred:
instance "snapcraft-pub-sub" does not exist
launch failed: Cannot read image format: qemu-img failed (Process returned exit code: 1) with output:
qemu-img: Could not open '/var/snap/multipass/common/cache/multipassd/vault/images/snapcraft-core18-٢٠٢٠١١١١/bionic-server-cloudimg-amd64-disk.img': Could not open '/var/snap/multipass/common/cache/multipassd/vault/images/snapcraft-core18-٢٠٢٠١١١١/bionic-server-cloudimg-amd64-disk.img': Permission denied

An error occurred with the instance when trying to launch with 'multipass': returned exit code 2.
Ensure that 'multipass' is setup correctly and try again.
```

**To Reproduce**
How, and what happened?
Typing the `snapcraft` command

**Expected behavior**
The expected behavior is to build a snap

**Logs**
Please provide logs from the daemon, see [accessing logs](https://multipass.run/docs/accessing-logs) on where to find them on your platform.

**Additional info**
 - OS: ubuntu 18.04
- `multipass   1.8.0`
- `multipass info --all`

**Additional context**
I made a fix around it by changing the language format of the system settings -> region & Language -> Formats, change it to US or UK or any other English format, I think it has a problem reading a directory with Arabic characters.

### PR DESCRIPTION
**Pull request by andrei-toterman**
The dates used by the image vault and custom image host are formatted in the system locale. This PR formats them using the C locale for consistency.

fix #2442

### CODE REVIEW

File: src/daemon/default_vm_image_vault.cpp [hunk 1]
```diff
@@ -355,9 +355,8 @@ mp::VMImage mp::DefaultVMImageVault::fetch_image(const FetchType& fetch_type, co
                 // Attempt to make a sane directory name based on the filename of the image
 
                 const auto image_dir_name =
-                    QString("%1-%2")
-                        .arg(image_filename.section(".", 0, image_filename.endsWith(".xz") ? -3 : -2))
-                        .arg(last_modified.toString("yyyyMMdd"));
+                    QString("%1-%2").arg(image_filename.section(".", 0, image_filename.endsWith(".xz") ? -3 : -2),
+                                         QLocale::c().toString(last_modified, "yyyyMMdd"));
```
Comment (luis4a0) [inline src/daemon/default_vm_image_vault.cpp:359]: This is perfectly correct, but could you please respect the structure `QString(...).arg(...).arg(...)` in order to modify only line 360? You can do `git rebase --interactive` to avoid adding one more commit, if you prefer.

**Review by luis4a0 — CHANGES_REQUESTED** [review]
Hey @andrei-toterman, thanks! One minor detail inline and we're done.

File: src/daemon/default_vm_image_vault.cpp (hunk 1 above)
Comment (andrei-toterman) [reply src/daemon/default_vm_image_vault.cpp:359]: Sure, but is that preferable? `QString(...).arg(...).arg(...)` involves the creation of two QStrings, while `QString(...).arg(..., ...)` involves only one.

**Review by luis4a0 — APPROVED** [review]
bors r+

**Comment by luis4a0** [comment]
:angry:

bors retry

**Comment by andrei-toterman** [comment]
bors retry

**Comment by andrei-toterman** [comment]
bors retry

**Comment by andrei-toterman** [comment]
i'm begging you :pray: 

bors retry

**Comment by luis4a0** [comment]
Last time. If it fails, I'll merge manually.

bors retry
