### PR TITLE
Ignore LXDNotFoundException on purge

### LINKED ISSUE #2714: Multipass crashes on `delete -p` when using the LXD driver
**Describe the bug**
Multipass crashes with an exception reaching a forbidden boundary when trying to purge-delete an instance. This happens after the instance has been successfully deleted in LXD and Multipass requests its state again. Presumably, that's coming out of [here](https://github.com/canonical/multipass/blob/main/src/platform/backends/lxd/lxd_virtual_machine.cpp#L199).

```
$ mp delete -p primary
delete failed: cannot connect to the multipass socket
Please ensure multipassd is running and '/var/snap/multipass/common/multipass_socket' is accessible
```

And this in the log, after the instance is deleted:

```
ago 23 17:28:12 ricab-xps13 multipassd[77722]: Requesting LXD: GET unix://multipass/var/snap/lxd/common/lxd/unix.socket@1.0/virtual-machines/primary/state?project=multipass
ago 23 17:28:12 ricab-xps13 multipass.multipassd[77722]: terminate called after throwing an instance of 'multipass::LXDNotFoundException'
ago 23 17:28:12 ricab-xps13 multipass.multipassd[77722]:   what():  LXD object not found
```

**To Reproduce**
How, and what happened?
1. `multipass set local.driver=lxd`
1. `multipass launch`
1. `multipass delete -p <instance>`

### PR DESCRIPTION
**Pull request by sharder996**
Ignore `LXDNotFoundException` which is thrown when an instance has been purged. This isn't a particularly nice fix, but seems to be the simplest without a complete refactor of the LXD backend. Another potential way of accounting for this situation could be through the use of the `update_shutdown_status` boolean, but I felt like that would just add unnecessary complexity to an already complex state machine.

Fixes #2714

### CODE REVIEW

File: src/platform/backends/lxd/lxd_virtual_machine.cpp [hunk 1]
```diff
@@ -196,22 +196,29 @@ mp::LXDVirtualMachine::~LXDVirtualMachine()
 {
     update_shutdown_status = false;
 
-    current_state();
-    if (state == State::running)
+    try
```
Comment (ricab) [inline src/platform/backends/lxd/lxd_virtual_machine.cpp:199]: An overall wrapping with `top_catch_all` would still be nice (in addition to the existing try/catches), to account for any other exceptions that could be thrown here and avoid terminating in the same way.

**Review by ricab — CHANGES_REQUESTED** [review]
Hey @sharder996, thanks for the fix! I think you're right, this is what we need for the time being. Only a few requests inline.

**Comment by ricab** [comment]
Hey @sharder996, I haven't looked back at this yet, but it seems it needs a rebase.

File: tests/lxd/test_lxd_backend.cpp [hunk 2]
```diff
@@ -653,6 +654,65 @@ TEST_F(LXDBackend, machine_does_not_update_state_in_dtor)
     EXPECT_TRUE(stop_requested);
 }
 
+TEST_F(LXDBackend, machine_logs_not_found_exception_in_dtor)
```
Comment (ricab) [inline tests/lxd/test_lxd_backend.cpp:657]: Could you use camelCase for this? We have a bunch of snake_cased tests still, but we're trying to move from it because gtest advises against underscores in test names (it can mess with how it uses underscores to generate internal test names).

File: tests/lxd/test_lxd_backend.cpp [hunk 3]
```diff
@@ -26,6 +26,7 @@
 #include "tests/mock_platform.h"
 #include "tests/mock_status_monitor.h"
 #include "tests/stub_status_monitor.h"
+#include "tests/stub_terminal.h"
```
Comment (ricab) [inline tests/lxd/test_lxd_backend.cpp:29]: Is this a leftover from development?

File: tests/lxd/test_lxd_backend.cpp [hunk 4]
```diff
@@ -653,6 +654,65 @@ TEST_F(LXDBackend, machine_does_not_update_state_in_dtor)
...
+    {
+        mp::LXDVirtualMachine machine{
+            default_description, mock_monitor,        mock_network_access_manager.get(), base_url,
+            bridge_name,         default_storage_pool};
+        machine.shutdown();
+    }
+
+    EXPECT_TRUE(vm_shutdown);
+    EXPECT_TRUE(stop_requested);
+}
```
Comment (ricab) [inline tests/lxd/test_lxd_backend.cpp:714]: I generally request that functions be kept small and copy-pasting code be avoided (the two go hand in hand). 

However, lets leave it alone in here: you are just reproducing the pattern that is used throughout the file and extracting reusable lambda bits for mocking is not obvious and not for this PR.

**Review by ricab — COMMENTED** [review]
Hey @sharder996, this is looking good now, I have only a couple of tiny requests before we ship it :wink: And I did not see any leaking mocks, BTW.

**Review by ricab — APPROVED** [review]
Alright, LGTM!

bors r+

**Comment by ricab** [comment]
bors retry
