### PR TITLE
Fix crash when purge deleting while starting

### LINKED ISSUE #3279: Multipass crashes when trying to delete purge an instance while it is starting
**Describe the bug**
The Multipass daemon crashes when trying to delete purge an instance while it is starting. This issue is most prevalent when the daemon is starting up and booting instances. Delete purging an instance during this time will cause the daemon to crash.

**To Reproduce**
1. `multipass start foo` (in terminal one)
2. `multipass delete -p --all` (in terminal two)

*or*

1. Start the Multipass daemon (must have an instance that was in the `Running` state when the daemon exited)
2. `multipass delete -p --all`

**Expected behavior**
Either the `delete` command waits for the `start` command to finish, or the `start` command is short circuited and the instance deleted instantly.

**Logs**
```
[2023-10-30T11:00:33.003] [debug] [foo] process working dir ''
[2023-10-30T11:00:33.003] [info] [foo] process program 'qemu-system-x86_64'
[2023-10-30T11:00:33.003] [info] [foo] process arguments '-bios, OVMF.fd, --enable-kvm, -cpu, host, -nic, tap,ifname=tap-85a8e535edf,script=no,downscript=no,model=virtio-net-pci,mac=52:54:00:0f:f3:72, -device, virtio-scsi-pci,id=scsi0, -drive, file=/root/.local/share/multipassd/vault/instances/foo/ubuntu-22.04-server-cloudimg-amd64.img,if=none,format=qcow2,discard=unmap,id=hda, -device, scsi-hd,drive=hda,bus=scsi0.0, -smp, 1, -m, 1024M, -qmp, stdio, -chardev, null,id=char0, -serial, chardev:char0, -nographic, -cdrom, /root/.local/share/multipassd/vault/instances/foo/cloud-init-config.iso'
[2023-10-30T11:00:33.018] [debug] [qemu-system-x86_64] [43090] started: qemu-system-x86_64 -nographic -dump-vmstate /tmp/multipassd.ubAeub
[2023-10-30T11:00:33.096] [debug] [daemon] Applied AppArmor policy: multipass.foo.qemu-system-x86_64
[2023-10-30T11:00:33.096] [info] [foo] process state changed to Starting
[2023-10-30T11:00:33.109] [info] [foo] process state changed to Running
[2023-10-30T11:00:33.109] [debug] [qemu-system-x86_64] [43092] started: qemu-system-x86_64 -bios OVMF.fd --enable-kvm -cpu host -nic tap,ifname=tap-85a8e535edf,script=no,downscript=no,model=virtio-net-pci,mac=52:54:00:0f:f3:72 -device virtio-scsi-pci,id=scsi0 -drive file=/root/.local/share/multipassd/vault/instances/foo/ubuntu-22.04-server-cloudimg-amd64.img,if=none,format=qcow2,discard=unmap,id=hda -device scsi-hd,drive=hda,bus=scsi0.0 -smp 1 -m 1024M -qmp stdio -chardev null,id=char0 -serial chardev:char0 -nographic -cdrom /root/.local/share/multipassd/vault/instances/foo/cloud-init-config.iso
[2023-10-30T11:00:33.109] [info] [foo] process started
[2023-10-30T11:00:33.110] [debug] [foo] Waiting for SSH to be up
[2023-10-30T11:00:33.195] [debug] [foo] QMP: {"QMP": {"version": {"qemu": {"micro": 0, "minor": 2, "major": 6}, "package": "Debian 1:6.2+dfsg-2ubuntu6.15"}, "capabilities": ["oob"]}}

[2023-10-30T11:00:33.232] [debug] [foo] QMP: {"return": {}}

[2023-10-30T11:00:34.112] [trace] [foo] ssh connection failed: 'Timeout connecting to 10.241.74.65'
[2023-10-30T11:00:34.706] [trace] [client cert store] Verifying cert:
-----BEGIN CERTIFICATE-----
MIIBizCCATECBL/cmrgwCgYIKoZIzj0EAwIwUDELMAkGA1UEBhMCVVMxEjAQBgNV
BAoMCUNhbm9uaWNhbDEtMCsGA1UEAwwkNDg3ZjM0ODYtYjEzOC00YWQ5LTg0NjQt
MmU0YTA5MTdkMWZhMB4XDTIyMDcxMTIxNTYwOVoXDTIzMDcxMTIxNTYwOVowUDEL
MAkGA1UEBhMCVVMxEjAQBgNVBAoMCUNhbm9uaWNhbDEtMCsGA1UEAwwkNDg3ZjM0
ODYtYjEzOC00YWQ5LTg0NjQtMmU0YTA5MTdkMWZhMFkwEwYHKoZIzj0CAQYIKoZI
zj0DAQcDQgAEml8G1TFmkdpkykRzDDP582JKA+9AvtC3Z4+X/mMXFi28U0pmmnME
rX+QqFIRyT3EjgP2FSg7pG3Hs0WCg00WJzAKBggqhkjOPQQDAgNIADBFAiAlzI0I
pZBbArmZOFW1hSd+QNPLY9OPhtZzKCeOyiFBlAIhAK2NEVrCSOUe/DpTKVFhkLwE
VE9wTOJxpkc8uKGq6C5h
-----END CERTIFICATE-----

[2023-10-30T11:00:35.089] [info] [foo] process state changed to NotRunning
[2023-10-30T11:00:35.089] [error] [foo] error: program: qemu-system-x86_64; error: Process crashed
[2023-10-30T11:00:35.281] [trace] [daemon] Removing AppArmor policy:

#include <tunables/global>
profile multipass.foo.qemu-system-x86_64 flags=(attach_disconnected) {
  #include <abstractions/base>
  #include <abstractions/consoles>
  #include <abstractions/nameservice>

  # required for reading disk images
  capability dac_override,
  capability dac_read_search,
  capability chown,

  # Enables modifying of file ownership and permissions
  capability fsetid,
  capability fowner,

  # needed to drop privileges
  capability setgid,
  capability setuid,

  network inet stream,
  network inet6 stream,

  # Allow multipassd send qemu signals
  signal (receive) peer=unconfined,

  /dev/net/tun rw,
  /dev/kvm rw,
  /dev/ptmx rw,
  /dev/kqemu rw,
  @{PROC}/*/status r,
  # When qemu is signaled to terminate, it will read cmdline of signaling
  # process for reporting purposes. Allowing read access to a process
  # cmdline may leak sensitive information embedded in the cmdline.
  @{PROC}/@{pid}/cmdline r,
  # Per man(5) proc, the kernel enforces that a thread may
  # only modify its comm value or those in its thread group.
  owner @{PROC}/@{pid}/task/@{tid}/comm rw,
  @{PROC}/sys/kernel/cap_last_cap r,
  owner @{PROC}/*/auxv r,
  @{PROC}/sys/vm/overcommit_memory r,

  # access to firmware's etc (selectively chosen for multipass' usage)
  /usr{,/local}/share/{seabios,ovmf,qemu,qemu-efi}/* r,

  # for save and resume
  /{usr/,}bin/dash rmix,
  /{usr/,}bin/dd rmix,
  /{usr/,}bin/cat rmix,

  # for restore
  /{usr/,}bin/bash rmix,

  # for file-posix getting limits since 9103f1ce
  /sys/devices/**/block/*/queue/max_segments r,

  # for gathering information about available host resources
  /sys/devices/system/cpu/ r,
  /sys/devices/system/node/ r,
  /sys/devices/system/node/node[0-9]*/meminfo r,
  /sys/module/vhost/parameters/max_mem_regions r,

  # binary and its libs
  /usr/bin/qemu-system-x86_64 ixr,
  /{,usr/}lib/{,@{multiarch}/}{,**/}*.so* rm,

  # CLASSIC ONLY: need to specify required libs from core snap
  /{,var/lib/snapd/}snap/core18/*/{,usr/}lib/@{multiarch}/{,**/}*.so* rm,

  # Disk images
  /root/.local/share/multipassd/vault/instances/foo/ubuntu-22.04-server-cloudimg-amd64.img rwk,  # QCow2 filesystem image
  /root/.local/share/multipassd/vault/instances/foo/cloud-init-config.iso rk,   # cloud-init ISO

  # allow full access just to user-specified mount directories on the host
  
}
    
[2023-10-30T11:00:35.287] [trace] [daemon] Removing AppArmor policy:

#include <tunables/global>
profile multipass.foo.qemu-system-x86_64 flags=(attach_disconnected) {
  #include <abstractions/base>
  #include <abstractions/consoles>
  #include <abstractions/nameservice>

  # required for reading disk images
  capability dac_override,
  capability dac_read_search,
  capability chown,

  # Enables modifying of file ownership and permissions
  capability fsetid,
  capability fowner,

  # needed to drop privileges
  capability setgid,
  capability setuid,

  network inet stream,
  network inet6 stream,

  # Allow multipassd send qemu signals
  signal (receive) peer=unconfined,

  /dev/net/tun rw,
  /dev/kvm rw,
  /dev/ptmx rw,
  /dev/kqemu rw,
  @{PROC}/*/status r,
  # When qemu is signaled to terminate, it will read cmdline of signaling
  # process for reporting purposes. Allowing read access to a process
  # cmdline may leak sensitive information embedded in the cmdline.
  @{PROC}/@{pid}/cmdline r,
  # Per man(5) proc, the kernel enforces that a thread may
  # only modify its comm value or those in its thread group.
  owner @{PROC}/@{pid}/task/@{tid}/comm rw,
  @{PROC}/sys/kernel/cap_last_cap r,
  owner @{PROC}/*/auxv r,
  @{PROC}/sys/vm/overcommit_memory r,

  # access to firmware's etc (selectively chosen for multipass' usage)
  /usr{,/local}/share/{seabios,ovmf,qemu,qemu-efi}/* r,

  # for save and resume
  /{usr/,}bin/dash rmix,
  /{usr/,}bin/dd rmix,
  /{usr/,}bin/cat rmix,

  # for restore
  /{usr/,}bin/bash rmix,

  # for file-posix getting limits since 9103f1ce
  /sys/devices/**/block/*/queue/max_segments r,

  # for gathering information about available host resources
  /sys/devices/system/cpu/ r,
  /sys/devices/system/node/ r,
  /sys/devices/system/node/node[0-9]*/meminfo r,
  /sys/module/vhost/parameters/max_mem_regions r,

  # binary and its libs
  /usr/bin/qemu-system-x86_64 ixr,
  /{,usr/}lib/{,@{multiarch}/}{,**/}*.so* rm,

  # CLASSIC ONLY: need to specify required libs from core snap
  /{,var/lib/snapd/}snap/core18/*/{,usr/}lib/@{multiarch}/{,**/}*.so* rm,

  # Disk images
  /root/.local/share/multipassd/vault/instances/foo/ubuntu-22.04-server-cloudimg-amd64.img rwk,  # QCow2 filesystem image
  /root/.local/share/multipassd/vault/instances/foo/cloud-init-config.iso rk,   # cloud-init ISO

  # allow full access just to user-specified mount directories on the host
  
}
    
[2023-10-30T11:00:35.287] [info] [apparmor] Failed to remove AppArmor policy 
#include <tunables/global>
profile multipass.foo.qemu-system-x86_64 flags=(attach_disconnected) {
  #include <abstractions/base>
  #include <abstractions/consoles>
  #include <abstractions/nameservice>

  # required for reading disk images
  capability dac_override,
  capability dac_read_search,
  capability chown,

  # Enables modifying of file ownership and permissions
  capability fsetid,
  capability fowner,

  # needed to drop privileges
  capability setgid,
  capability setuid,

  network inet stream,
  network inet6 stream,

  # Allow multipassd send qemu signals
  signal (receive) peer=unconfined,

  /dev/net/tun rw,
  /dev/kvm rw,
  /dev/ptmx rw,
  /dev/kqemu rw,
  @{PROC}/*/status r,
  # When qemu is signaled to terminate, it will read cmdline of signaling
  # process for reporting purposes. Allowing read access to a process
  # cmdline may leak sensitive information embedded in the cmdline.
  @{PROC}/@{pid}/cmdline r,
  # Per man(5) proc, the kernel enforces that a thread may
  # only modify its comm value or those in its thread group.
  owner @{PROC}/@{pid}/task/@{tid}/comm rw,
  @{PROC}/sys/kernel/cap_last_cap r,
  owner @{PROC}/*/auxv r,
  @{PROC}/sys/vm/overcommit_memory r,

  # access to firmware's etc (selectively chosen for multipass' usage)
  /usr{,/local}/share/{seabios,ovmf,qemu,qemu-efi}/* r,

  # for save and resume
  /{usr/,}bin/dash rmix,
  /{usr/,}bin/dd rmix,
  /{usr/,}bin/cat rmix,

  # for restore
  /{usr/,}bin/bash rmix,

  # for file-posix getting limits since 9103f1ce
  /sys/devices/**/block/*/queue/max_segments r,

  # for gathering information about available host resources
  /sys/devices/system/cpu/ r,
  /sys/devices/system/node/ r,
  /sys/devices/system/node/node[0-9]*/meminfo r,
  /sys/module/vhost/parameters/max_mem_regions r,

  # binary and its libs
  /usr/bin/qemu-system-x86_64 ixr,
  /{,usr/}lib/{,@{multiarch}/}{,**/}*.so* rm,

  # CLASSIC ONLY: need to specify required libs from core snap
  /{,var/lib/snapd/}snap/core18/*/{,usr/}lib/@{multiarch}/{,**/}*.so* rm,

  # Disk images
  /root/.local/share/multipassd/vault/instances/foo/ubuntu-22.04-server-cloudimg-amd64.img rwk,  # QCow2 filesystem image
  /root/.local/share/multipassd/vault/instances/foo/cloud-init-config.iso rk,   # cloud-init ISO

  # allow full access just to user-specified mount directories on the host
  
}
    : errno=254 ()
Segmentation fault (core dumped)
```

**Additional info**
 - OS: Ubuntu Linux
- `multipass version`: dev build
- `multipass get local.driver`: `qemu`

### PR DESCRIPTION
**Pull request by Sploder12**
resolves #3279 

There are several sources of crashes when running `delete -p` and `start` at the same time.
One source stems from a race condition in the daemon involving multiple reads and writes to `operative_instances` concurrently. The crash source is from a callback created in `on_restart` which can unsafely write into `operative_instances` if the instance has been deleted. A workaround is to ensure this is always a read operation and catching the resulting error, but this still causes UB and puts the thread in a corrupt state. Preventing the callback or having safe access into the `operative_instances` map would be better.
  
Another is from callbacks in the `QemuVirtualMachine` which are called during or after the destruction of the VM instance. This is addressed by disconnecting the callbacks so they are not called when they shouldn't be and reconnecting them when appropriate.

### CODE REVIEW

File: src/platform/backends/qemu/qemu_virtual_machine.cpp [hunk 1]
```diff
@@ -670,6 +628,63 @@ void mp::QemuVirtualMachine::initialize_vm_process()
     });
 }
 
+void mp::QemuVirtualMachine::connect_signals()
+{
+    auto connection_type = static_cast<Qt::ConnectionType>(Qt::QueuedConnection | Qt::UniqueConnection);
```
Comment (andrei-toterman) [inline src/platform/backends/qemu/qemu_virtual_machine.cpp:633]: Check the note here https://doc.qt.io/qt-6/qobject.html#connect stating that "Qt::UniqueConnections do not work for lambdas, non-member functions and functors; they only apply to connecting to member functions.". I did an experiment and indeed the connections are not valid. Unfortunately you're going to need a different mechanism for this :neutral_face:

**Review by andrei-toterman — CHANGES_REQUESTED** [review]

**Review by andrei-toterman — APPROVED** [review]
Alright, LGTM. Thanks, @Sploder12!
