### PR TITLE
Fix inconsistent `list` output

### LINKED ISSUE #2464: make `multipass list --format csv|json|yaml` output consistent
**What are you trying to do?**
I am wrapping multipass in another tool and found some inconsistencies in the output of the `info` subcommand when using the `--format` flag. Without the format flag, list shows the image name, but when using --format it only shows the release, e.g.:

```
$ multipass list
Name                     State             IPv4             Image
primary                  Running           192.168.64.24    Ubuntu 20.04 LTS
bionic                   Stopped           --               Ubuntu 18.04 LTS
openvpn                  Running           192.168.64.15    Ubuntu 20.04 LTS
                                           192.168.254.1
ssh-audit-logger-bionic  Running           192.168.64.27    Ubuntu 18.04 LTS
ssh-audit-logger-focal   Running           192.168.64.28    Ubuntu 20.04 LTS
``` 

The output of `multipass list --format json`:

```json
{
    "list": [
        {
            "ipv4": [
                "192.168.64.28"
            ],
            "name": "ssh-audit-logger-focal",
            "release": "20.04 LTS",
            "state": "Running"
        },
        {
            "ipv4": [
                "192.168.64.15",
                "192.168.254.1"
            ],
            "name": "openvpn",
            "release": "20.04 LTS",
            "state": "Running"
        },
        {
            "ipv4": [
            ],
            "name": "bionic",
            "release": "18.04 LTS",
            "state": "Stopped"
        },
        {
            "ipv4": [
                "192.168.64.24"
            ],
            "name": "primary",
            "release": "20.04 LTS",
            "state": "Running"
        },
        {
            "ipv4": [
                "192.168.64.27"
            ],
            "name": "ssh-audit-logger-bionic",
            "release": "18.04 LTS",
            "state": "Running"
        }
    ]
}
```

It is the same for `csv`, `yaml`, and `json` output.

**What's your proposed solution?**
It would be good to output both the release and image in all formats.

**Additional context**
Other outputs for reference:

```csv
multipass list --format csv
Name,State,IPv4,IPv6,Release,AllIPv4
primary,Running,192.168.64.24,,20.04 LTS,"192.168.64.24"
bionic,Stopped,,,18.04 LTS,""
openvpn,Running,192.168.64.15,,20.04 LTS,"192.168.64.15,192.168.254.1"
ssh-audit-logger-bionic,Running,192.168.64.27,,18.04 LTS,"192.168.64.27"
ssh-audit-logger-focal,Running,192.168.64.28,,20.04 LTS,"192.168.64.28"
```

```yaml
primary:
  - state: Running
    ipv4:
      - 192.168.64.24
    release: 20.04 LTS
bionic:
  - state: Stopped
    ipv4:
      []
    release: 18.04 LTS
openvpn:
  - state: Running
    ipv4:
      - 192.168.64.15
      - 192.168.254.1
    release: 20.04 LTS
ssh-audit-logger-bionic:
  - state: Running
    ipv4:
      - 192.168.64.27
    release: 18.04 LTS
ssh-audit-logger-focal:
  - state: Running
    ipv4:
      - 192.168.64.28
    release: 20.04 LTS

```

### PR DESCRIPTION
**Pull request by sharder996**
Fixes `list` output so that all formats output `release` + `image` for the `release` field. eg.
```
ubuntu:build$ multipass list --format yaml
foo:
  - state: Running
    ipv4:
      - 10.3.183.81
    release: Ubuntu 20.04 LTS
persuasive-ruff:
  - state: Deleted
    ipv4:
      []
    release: Not Available
```
Fixes #2464

### CODE REVIEW

File: src/client/cli/formatter/csv_formatter.cpp [hunk 1]
```diff
@@ -56,10 +56,11 @@ std::string mp::CSVFormatter::format(const ListReply& reply) const
...
     for (const auto& instance : format::sorted(reply.instances()))
     {
-        fmt::format_to(buf, "{},{},{},{},{},\"{}\"\n", instance.name(),
-                       mp::format::status_string_for(instance.instance_status()),
-                       instance.ipv4_size() ? instance.ipv4(0) : "", instance.ipv6_size() ? instance.ipv6(0) : "",
-                       instance.current_release(), fmt::join(instance.ipv4(), ","));
+        fmt::format_to(
+            buf, "{},{},{},{},{},\"{}\"\n", instance.name(), mp::format::status_string_for(instance.instance_status()),
+            instance.ipv4_size() ? instance.ipv4(0) : "", instance.ipv6_size() ? instance.ipv6(0) : "",
+            instance.current_release().empty() ? "Not Available" : fmt::format("Ubuntu {}", instance.current_release()),
```
Comment (larstobi) [inline src/client/cli/formatter/csv_formatter.cpp:62]: Would this hardcode "Ubuntu" in all output, even if it's a different distro?

Comment (townsend2010) [reply src/client/cli/formatter/csv_formatter.cpp:62]: This information comes from https://cloud-images.ubuntu.com/releases/streams/v1/com.ubuntu.cloud:released:download.json and *only* Ubuntu images are available there.  If one launches a different distro via `https://` or `file://`, we have no insight as to what the distro is, so we use `Not Available`.

Comment (larstobi) [reply src/client/cli/formatter/csv_formatter.cpp:62]: Ah, okay, so it exclusively hardcodes the printout "Ubuntu" for releases from the stream at ubuntu.com, and will print "Not Available" for anything else. Got it! Thanks for the explanation.

Just to be sure, this is the formatting for `multipass list`, and not `multipass find`?

Also, the information that this is "ubuntu" is available in that `cloud-images.ubuntu.com` stream under the key `os`.

Though, upon launching an image, the `os` key is not stored in `multipassd-vm-instances.json`:

`multipassd-vm-instances.json`
```json
{
    "example": {
        "image": {
            "aliases": [
            ],
            "current_release": "",
            "id": "e1ce033239f0038dca5ef09e582762ba0d0dfdedc1d329bc51bb0e9f5057af9d",
            "initrd_path": "",
            "kernel_path": "",
            "original_release": "22.04 LTS",
            "path": "/var/root/Library/Application Support/multipassd/qemu/vault/instances/example/ubuntu-22.04-server-cloudimg-arm64.img",
            "release_date": "20220712"
        },
        "last_accessed": 1658837383975983,
        "query": {
            "persistent": false,
            "query_type": 0,
            "release": "jammy",
            "remote_name": ""
        }
    }
}
```

Would it be an option to store the `os` key in `multipassd-vm-instances.json` and use that?

Comment (townsend2010) [reply src/client/cli/formatter/csv_formatter.cpp:62]: Hey @larstobi,

> Just to be sure, this is the formatting for `multipass list`, and not `multipass find`?

Yes, this PR **only** applies to `multipass list`.

> Would it be an option to store the `os` key in `multipassd-vm-instances.json` and use that?

Yes, it's possible, but IMO is outside the scope of this PR.  Two things would need to be considered though.  One is to use this current behavior in already existing instances that would be missing the `os` key and the second is to make sure `ubuntu` is capitalized when resolving the `os` key on output.

**Review by townsend2010 — APPROVED** [review]
LGTM, thanks!

bors merge

**Comment by townsend2010** [comment]
bors cancel

File: src/client/cli/formatter/csv_formatter.cpp [hunk 2]
```diff
@@ -92,7 +93,9 @@ std::string mp::CSVFormatter::format(const FindReply& reply) const
 
         mp::format::filter_aliases(aliases);
 
-        auto image_id = aliases[0].remote_name().empty() ? aliases[0].alias() : fmt::format("{}:{}", aliases[0].remote_name(), aliases[0].alias());
+        auto image_id = aliases[0].remote_name().empty()
+                            ? aliases[0].alias()
+                            : fmt::format("{}:{}", aliases[0].remote_name(), aliases[0].alias());
```
Comment (townsend2010) [inline src/client/cli/formatter/csv_formatter.cpp:98]: Is this just a drive by `clang-format` change?

Comment (sharder996) [reply src/client/cli/formatter/csv_formatter.cpp:98]: That's what it looks like. Not seeing any other differences.

Comment (townsend2010) [reply src/client/cli/formatter/csv_formatter.cpp:98]: Ok, thanks.

**Comment by townsend2010** [comment]
bors merge

**Comment by townsend2010** [comment]
Try again...

bors retry

**Comment by townsend2010** [comment]
Again...

bors retry
