### PR TITLE
[utils] Pass timeout when getting ssh_hostname() in wait_until_ssh_up()

### LINKED ISSUE #2113: [daemon] `--timeout` not respected in IP determination
We're seeing both `lxd` and `qemu` backends failing to respect the `--timeout` passed:

```plain
Tue, 18 May 2021 13:28:25 GMT multipass start --timeout 1200
...
Tue, 18 May 2021 13:34:58 GMT launch failed: The following errors occurred:
Tue, 18 May 2021 13:35:08 GMT failed to determine IP address
```

### PR DESCRIPTION
**Pull request by townsend2010**
Fixes #2113

### CODE REVIEW

File: src/utils/utils.cpp [hunk 1]
```diff
@@ -243,7 +243,7 @@ void mp::utils::wait_until_ssh_up(VirtualMachine* virtual_machine, std::chrono::
                                   std::function<void()> const& ensure_vm_is_running)
 {
     mpl::log(mpl::Level::debug, virtual_machine->vm_name,
-             fmt::format("Trying SSH on {}:{}", virtual_machine->ssh_hostname(), virtual_machine->ssh_port()));
+             fmt::format("Trying SSH on {}:{}", virtual_machine->ssh_hostname(timeout), virtual_machine->ssh_port()));
```
Comment (Saviq) [inline src/utils/utils.cpp:246]: Shouldn't we just _not_ call `::ssh_hostname()` here? Like… we have the `try_action_for()` below that's meant to handle timeouts. Worst case we'll wait 2*timeout here.

Comment (townsend2010) [reply src/utils/utils.cpp:246]: What would we call instead?  This for *only* getting the hostname/IP address and not for seeing when SSH is up and running.

Comment (townsend2010) [reply src/utils/utils.cpp:246]: Or ditch the log message or at least remove the IP/port info?

Comment (townsend2010) [reply src/utils/utils.cpp:246]: Also, if not here, then the timeout will have to be added to
https://github.com/canonical/multipass/blob/d8d8b2149d8b72a1d9509929e0527d21ac7eddd8/src/utils/utils.cpp#L251
instead.

So, let me know how you prefer this to be handled.

Comment (Saviq) [reply src/utils/utils.cpp:246]: > Or ditch the log message or at least remove the IP/port info?

Yeah, we shouldn't block in this just to log it. Can log after we get the info in the action.

> Also, if not here, then the timeout will have to be added to

Will it? Isn't `try_action_for` dealing with that exactly?

Comment (townsend2010) [reply src/utils/utils.cpp:246]: Actually, having discovered the LXD instance creation timeout and fixing that by moving it into `ensure_vm_is_running()`, I think this message should not include the hostname/IP address & port info.

Comment (townsend2010) [reply src/utils/utils.cpp]: Ok, I modified this message to not get the hostname/port and just log a generic message.  I also modified the subsequent `ssh_hostname()` call to have a 1ms timeout so it will use this action instead of the one built into `ssh_hostname()`.

File: src/utils/utils.cpp [hunk 2]
```diff
@@ -242,13 +244,12 @@ bool mp::utils::valid_mac_address(const std::string& mac)
...
 {
-    mpl::log(mpl::Level::debug, virtual_machine->vm_name,
-             fmt::format("Trying SSH on {}:{}", virtual_machine->ssh_hostname(), virtual_machine->ssh_port()));
+    mpl::log(mpl::Level::debug, virtual_machine->vm_name, "Waiting for SSH to be up");
     auto action = [virtual_machine, &ensure_vm_is_running] {
         ensure_vm_is_running();
         try
         {
-            mp::SSHSession session{virtual_machine->ssh_hostname(), virtual_machine->ssh_port()};
+            mp::SSHSession session{virtual_machine->ssh_hostname(1ms), virtual_machine->ssh_port()};
```
Comment (Saviq) [inline src/utils/utils.cpp:252]: Should we add a debug line after this saying something like "Found instance hostname: … port: …"?

**Review by Saviq — COMMENTED** [review]
In all the other calls to `ssh_hostname()` we're OK not having a specific timeout? If not, worth filing an issue?

**Comment by townsend2010** [comment]
> In all the other calls to ssh_hostname() we're OK not having a specific timeout?

This is the first time `ssh_hostname()` is called, so either we'll get an IP address here and all other `ssh_hostname()` calls will return quickly or they will have the default 2 minute timeout.  So the question is if we want all the others to timeout quickly or not.  I have not looked into those to see what they are doing.

File: src/utils/utils.cpp (hunk 2 above)
Comment (townsend2010) [reply src/utils/utils.cpp:252]: I don't think it's necessary since this is just testing for an ssh connection, not getting the IP address.  If we want to log the IP address discovery, that should probably go in `ip_address_for()`, but that seems to be unrelated to this PR.

**Review by Saviq — APPROVED** [review]
> So the question is if we want all the others to timeout quickly or not.

IIRC we cache it, so as long as it succeeds once, the remaining calls will be immediate.

bors merge

**Comment by Saviq** [comment]
Let the ball roll…

bors retry

**Comment by Saviq** [comment]
bors retry

**Comment by townsend2010** [comment]
bors retry
