### PR TITLE
Fix duplicate newline in CLI failure output when details end with new…

### LINKED ISSUE #2147: Multipass outputs inconsistent number of empty lines on different errors
**Describe the bug**
The CLI outputs inconsistent number of empty lines on different errors.

```plain
ricab@ricab-xps13:~ $ multipass launch --disk 1g
launch failed: Requested disk (1073741824 bytes) below minimum for this image (2361393152 bytes)
ricab@ricab-xps13:~ $ multipass start asdf
start failed: instance(s) missing
Instance 'asdf' does not exist.

ricab@ricab-xps13:~ $ multipass launch --name primary
launch failed: instance "primary" already exists


ricab@ricab-xps13:~ $
```

Zero or one is pretty unnoticeable, but two feels excessive. 

**Additional info**
```
$ multipass version
multipass  1.6.2
multipassd 1.6.2
```

### PR DESCRIPTION
**Pull request by ShadiBahaa**
## Description

This PR normalizes how `standard_failure_handler_for` prints `error_details` so the CLI does not emit an extra blank line before the shell prompt when callers already end each detail line with a newline.

**What does this PR do?** Trims trailing `\r` and `\n` characters from `error_details`, then appends a single final newline when formatting stderr output.

**Why is this change needed?** `standard_failure_handler_for` previously used `fmt::format("{}\n", error_details)`. Commands such as `start` whose `error_details` already end in `\n` (e.g. `absent_error_fmt`) produced `\n\n` after the last visible line, so users saw one extra blank line compared to failures with no detail block (e.g. duplicate instance name on launch). This matches the behavior described in #2147 and the maintainer note that the issue was improved but not fully fixed.

## Related Issue

Closes #2147

## Testing

**Unit test:** Added `StandardFailureHandlerFormatting.singleTrailingNewlineWhenDetailsAlreadyEndWithNewline` in `tests/unit/test_client_common.cpp`, asserting that `error_details` ending with `\n` still results in exactly one trailing newline.

**Manual testing steps:**

1. Build the Multipass client from this branch (per project build instructions).
2. Run a command that triggers `standard_failure_handler_for` with multi-line details, e.g. `multipass start <nonexistent>` — expect no extra blank line before the shell prompt compared to a single-line failure such as a duplicate `launch --name`.
3. Optionally compare stderr capture or terminal scrollback before/after to confirm only one newline terminates the message block.

**Screenshots:** N/A — stderr text layout only, no UI change.

## Checklist

- [x] My code follows the [contributing guidelines](https://github.com/canonical/multipass/blob/main/CONTRIBUTING.md)
- [x] I have signed the [Canonical CLA](https://canonical.com/legal/contributors)
- [x] I have added unit tests or no new ones were appropriate
- [ ] I have added integration tests or no new ones were appropriate
- [ ] I have updated documentation or no changes were appropriate
- [x] I have tested the changes locally or no specific testing was appropriate

### CODE REVIEW

File: src/client/common/client_common.cpp [hunk 1]
```diff
@@ -92,7 +106,7 @@ mp::ReturnCode mp::cmd::standard_failure_handler_for(const std::string& command,
                "{} failed: {}\n{}",
                command,
                status.error_message(),
-               !error_details.empty() ? fmt::format("{}\n", error_details) : "");
```
Comment (xmkg) [inline src/client/common/client_common.cpp:95]: The proposed solution works, but you can do the same with the following one-liner:

```c++
error_details + (error_details.empty() || error_details.ends_with('\n') ? "" : "\n")
```

Comment (ShadiBahaa) [reply src/client/common/client_common.cpp:95]: That's right but my current code does two extra things intentionally:

- strips all trailing \n and \r (not just checks one final \n)
- normalizes output to exactly one trailing newline for any non-empty detail

Comment (xmkg) [reply src/client/common/client_common.cpp:95]: Stripping all \r\n is not necessary, but a nice addition. You can still simplify it though:

```c++
    auto trimmed = std::string_view(error_details).substr(0, error_details.find_last_not_of("\r\n") + 1);

    fmt::print(cerr,
               "{} failed: {}\n{}",
               command,
               status.error_message(),
               trimmed.empty() ? "" : fmt::format("{}\n", trimmed));
```

**Review by xmkg — CHANGES_REQUESTED** [review]

File: src/client/common/client_common.cpp (hunk 1 above)
Comment (ShadiBahaa) [reply src/client/common/client_common.cpp:95]: Done

File: tests/unit/test_client_common.cpp [hunk 2]
```diff
@@ -129,3 +131,16 @@ TEST(TestClientHandleUserPassword, defaultHasNoPassword)
...
     mp::cmd::handle_password(client.get(), &term);
 }
+
+TEST(StandardFailureHandlerFormatting, singleTrailingNewlineWhenDetailsAlreadyEndWithNewline)
+{
+    std::stringstream cerr_stream;
+    grpc::Status status{grpc::StatusCode::ABORTED, "instance(s) missing", ""};
+
+    mp::cmd::standard_failure_handler_for(
+        "start", cerr_stream, status, "Instance 'asdf' does not exist.\n");
```
Comment (xmkg) [inline tests/unit/test_client_common.cpp]: Could you also add multiple CRLF's to confirm that all of them are stripped and only one is added? e.g. 
"Instance 'asdf' does not exist.\r\n\r\n\r"

Comment (ShadiBahaa) [reply tests/unit/test_client_common.cpp]: Done

**Review by xmkg — DISMISSED** [review]
LGTM. I'm okay with this as long as the pipeline is green, too. Thanks for the contribution, @ShadiBahaa, greatly appreciated!

**Comment by xmkg** [comment]
@ShadiBahaa There are three things to fix in the pipeline:

1-) Signing the CLA: You can follow the steps [here](https://canonical.com/legal/contributors)
2-) The [lint step](https://github.com/canonical/multipass/actions/runs/24365102551/job/71154953744?pr=4817) failure
3-) [Commit message linter](https://github.com/canonical/multipass/actions/runs/24365102094/job/71154923326?pr=4817) failure

**Comment by jimporter** [comment]
@ShadiBahaa When filling out the checklist in the PR template, please be sure to include all the items. It looks like you missed the one about AI contributions. For more information about our AI contribution guidelines, see [here](https://github.com/canonical/multipass/blob/main/CONTRIBUTING.md#ai).

**Comment by ShadiBahaa** [comment]
@xmkg Can u please approve it again? I pushed a new commit containing the lint and commit message fixes

**Review by xmkg — APPROVED** [review]

**Comment by xmkg** [comment]
Force-merged this based on CI results. CLI tests dispatch fails due to the MacOS package not being available -- we can't run the CLI tests on MacOS CI anyway.
