### PR TITLE
[ubuntu_image_host] Only reject multiple hash matches if not a full hash

### LINKED ISSUE #2072: [lxd] wrong release listed
```plain
$ multipass launch hirsute
Launched: tickled-pademelon                                                     

$ multipass exec tickled-pademelon -- lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 21.04
Release:        21.04
Codename:       hirsute

$ multipass list
Name                    State             IPv4             Image
tickled-pademelon       Running           10.152.94.219    Ubuntu 20.04 LTS

$ multipass info --all
Name:           tickled-pademelon
State:          Running
IPv4:           10.152.94.219
Release:        Ubuntu 21.04
Image hash:     58db5edffed2 (Ubuntu 20.04 LTS)
Load:           0.03 0.09 0.04
Disk usage:     1.2G out of 9.5G
Memory usage:   120.3M out of 982.8M
```

See the `Image` / `Image hash` bits ¯\\_(ツ)_/¯

### PR DESCRIPTION
**Pull request by townsend2010**
It's possible that the same full hash will exist in both the release and daily remotes, so don't reject it.

Fixes #2072

### CODE REVIEW

File: src/daemon/ubuntu_image_host.cpp [hunk 1]
```diff
@@ -83,14 +83,18 @@ mp::optional<mp::VMImageInfo> mp::UbuntuVMImageHost::info_for(const Query& query
...
-    else if (images.size() != 0)
-        return images.front().second;
-    else
+    if (images.size() == 0)
         return nullopt;
+
+    auto key = key_from(query.release);
+    auto image_id = images.front().second.id;
+
+    // If more than one match and query is a hash but not a full hash, throw an exception
```
Comment (Saviq) [inline src/daemon/ubuntu_image_host.cpp:92]:
```suggestion
    // If a partial hash query matches more than once, throw an exception
```

**Review by Saviq — CHANGES_REQUESTED** [review]
Any chance for a test?

**Comment by townsend2010** [comment]
> Any chance for a test?

Yeah, probably should make a test specific for this case.

**Comment by townsend2010** [comment]
Ok, tests added to hopefully check the conditions this is fixing.

**Review by Saviq — APPROVED** [review]
Looks legit!

bors merge

**Comment by townsend2010** [comment]
bors retry

**Comment by townsend2010** [comment]
bors retry

**Comment by townsend2010** [comment]
Ok, I'm just going to wait until #2118 gets merged before trying this anymore.

**Comment by townsend2010** [comment]
bors retry
