### PR TITLE
[3rd-party images] include qcow2 files when cloning

### LINKED ISSUE #4271: [qemu] cannot clone instances launched by file or URL
Trying to clone an instance that was launched with a file or URL results in the following error:

```
% multipass clone test
clone failed: Cannot list snapshots from the image: qemu-img failed (Process returned exit code: 1) with output:
qemu-img: Could not open '/var/root/Library/Application Support/multipassd/qemu/vault/instances/test-clone1/debian-12-generic-arm64.qcow2': Could not open '/var/root/Library/Application Support/multipassd/qemu/vault/instances/test-clone1/debian-12-generic-arm64.qcow2': No such file or directory
```

**To Reproduce**
How, and what happened?
1. `multipass launch -n test https://cloud.debian.org/images/cloud/bookworm/latest/debian-12-generic-arm64.qcow2`
2. `multipass stop test`
3. `multipass clone test`

**Expected behavior**
I should be able to clone an instance no matter its original source.

**Additional info**
ARM macOS 15, multipass v1.16.0

### PR DESCRIPTION
**Pull request by sharder996**
Debian and Fedora ship their cloud images with the `.qcow2` file extension which does not get picked up by `multipass clone`.

Fixes #4271 

---

MULTI-2150

### CODE REVIEW

File: tests/qemu/test_qemu_backend.cpp [hunk 1]
```diff
@@ -1245,7 +1245,7 @@ TEST_F(QemuBackend, removeAllSnapshotsFromTheImage)
                 last2ndProcessInfo.arguments.contains("@s2"));
 }
 
-TEST_F(QemuBackend, createVmAndCloneInstanceDirData)
+TEST_F(QemuBackend, cloneCopiesRelevantFiles)
```
Comment (ricab) [inline tests/qemu/test_qemu_backend.cpp:1248]: :pray:

**Review by xmkg — APPROVED** [review]
Tested locally, the qcow2 file(s) present in the instance dir are being copied to the clone.
