### PR TITLE
Fix IP listing in jammy instances

### LINKED ISSUE #2694: Multipass fails to detect extra IP on jammy - works on bionic and focal
**Describe the bug**
On Mac (haven't tested elsewhere)

% multipass launch bionic -n btest --network en0
Launched: btest                                                                 
% multipass launch focal -n ftest --network en0
Launched: ftest                                                                 
% multipass launch jammy -n jtest --network en0
Launched: jtest                                                                 

% multipass ls
Name                    State             IPv4             Image
btest                   Running           192.168.64.16    Ubuntu 18.04 LTS
                                          192.168.0.169
ftest                   Running           192.168.64.17    Ubuntu 20.04 LTS
                                          192.168.0.170
jtest                   Running           192.168.64.18    Ubuntu 22.04 LTS

* note no bridged network on jammy, but fine on bionic and focal.

**To Reproduce**
see steps above

**Expected behavior**
Get a bridged network in all cases

**Logs**
no errors

**Additional info**
% multipass version
multipass   1.10.1+mac
multipassd  1.10.1+mac

### PR DESCRIPTION
**Pull request by luis4a0**
Fixes #2694.

### CODE REVIEW

File: src/platform/backends/shared/base_virtual_machine.cpp [hunk 1]
```diff
@@ -41,7 +41,8 @@ std::vector<std::string> BaseVirtualMachine::get_all_ipv4(const SSHKeyProvider&
             ip_a_output = QString::fromStdString(
                 mpu::run_in_ssh_session(session, "ip -brief -family inet address show scope global"));
 
-            QRegularExpression ipv4_re{QStringLiteral("([\\d\\.]+)\\/\\d+\\s*$"), QRegularExpression::MultilineOption};
+            QRegularExpression ipv4_re{QStringLiteral("([\\d\\.]+)\\/\\d+\\s*(metric \\d+)?\\s*$"),
```
Comment (ricab) [inline src/platform/backends/shared/base_virtual_machine.cpp:44]: As discussed, `ip -json` would be a better option in the long run, if we start getting more similar problems. But this is fine for now.
