### PR TITLE
[daemon] Call hypervisor_health_check() in ctor

### LINKED ISSUE #2401: Creating instance with LXD fails after snap refresh
**Describe the bug**
After succesfully creating an instance, trying to create a new one failed.

**To Reproduce**
This situation showed up randomly, I'm not sure how to reproduce. In my case, I first created a VM with
`multipass launch -c 1 -d 10G -n testfs1lxd`

Then, trying to create a new one with
`multipass launch -c 4 -d 10G -n testfs4lxd`
gave
```
[2022-01-20T14:34:55.777] [error] [lxd request] Operation completed with error: (400) Failed creating instance record: Invalid devices: Device validation failed for "root": Root disk entry must have a "pool" property set
launch failed: Operation completed with error: (400) Failed creating instance record: Invalid devices: Device validation failed for "root": Root disk entry must have a "pool" property set
```

**Expected behavior**
A new instance running would be expected. However, `multipass list` shows the new instance in `unknown` state.

**Logs**
[Here](https://pastebin.ubuntu.com/p/hNCGCf6mvF/)

**Additional info**
Ubuntu 21.10
```
multipass version
multipass   1.9.0-dev.338+ga1ea65fb
```

**Additional context**
```
lxd --version
4.22
```

### PR DESCRIPTION
**Pull request by townsend2010**
This will try to ensure the backend is set up before launching any instances.

Fixes #2401

### CODE REVIEW

File: src/daemon/daemon.cpp [hunk 1]
```diff
@@ -1053,6 +1053,15 @@ mp::Daemon::Daemon(std::unique_ptr<const DaemonConfig> the_config)
...
     });
     source_images_maintenance_task.start(config->image_refresh_timer);
+
+    try
+    {
+        config->factory->hypervisor_health_check();
+    }
+    catch (const std::runtime_error& e)
+    {
+        mpl::log(mpl::Level::warning, category, fmt::format("Hypervisor health check failed: {}", e.what()));
```
Comment (Saviq) [inline src/daemon/daemon.cpp:1063]: Should this be warning, or error even?

Comment (townsend2010) [reply src/daemon/daemon.cpp:1063]: Well, it is `warning` :slightly_smiling_face:

I refrained from `error` since it's not really fatal since `hypervisor_health_check()'` will run again when an instance starts/launches and that is surfaced to the client in order for the user to take action.  It's probably splitting hairs between those two log severity values though...

Comment (townsend2010) [reply src/daemon/daemon.cpp:1063]: Or, after re-reading what you said, perhaps you mean it should be a lesser severity like `info` or something?

Comment (Saviq) [reply src/daemon/daemon.cpp:1063]: No no, I did mean warning or error, I just somehow looked for `mpl::warning()` ;P

**Review by Saviq — APPROVED** [review]
Yup.

bors merge

File: src/daemon/daemon.cpp (hunk 1 above)
Comment (townsend2010) [reply src/daemon/daemon.cpp:1063]: lol, ok

**Comment by townsend2010** [comment]
Hmm, some Codecov upload issue.  Try again...

bors retry
