### PR TITLE
[gui] Enhance FFI library loading

### LINKED ISSUE #4175: [GUI] Display a proper error message when "libdart_ffi"  library fails to load
**Describe the bug**
Sometimes, the GUI executable is unable to locate the libdart_ffi library for one reason or another. In that case, the GUI becomes stuck on displaying "Waiting for daemon..." forever, which is confusing and gives the impression that the daemon could not be reached.

**To Reproduce**
How, and what happened?
1. Relocate libdart_ffi[.so|.dll|.dylib) to a location that's not on the GUI's library search path
1. Launch the GUI

**Expected behavior**
The GUI should raise a fatal error indicating that it failed to load the libdart_ffi library, and close itself.

### PR DESCRIPTION
**Pull request by levkropp**
resolves #4175 

image

This pull request introduces changes to improve error handling and user experience when the FFI library fails to load. The updates include a new mechanism to detect FFI availability, enhancements to the `DaemonUnavailable` widget, and modifications to providers for better integration.

### Error Handling for FFI Library:

* [`src/client/gui/lib/ffi.dart`](diffhunk://#diff-0a91f284d9074caf859890b9d92d83e3eaeb2963f74491605435b5124bf5107bL20-R53): Introduced the `FFILibrary` class to encapsulate FFI library loading logic, handle errors gracefully, and provide utility methods (`isFFIAvailable` and `ffiLoadError`) for checking availability and accessing load errors.

### User Interface Enhancements:

* [`src/client/gui/lib/daemon_unavailable.dart`](diffhunk://#diff-45e88b27cc58ea15345a9f1736ad4d77b8f8ccf5eaa3fa0c85572876cad76a81R15-R74): Updated the `DaemonUnavailable` widget to display a fatal error message and an "Exit Application" button when the FFI library fails to load. Added a conditional check for `ffiAvailableProvider` to differentiate between fatal errors and regular daemon unavailability. [[1]](diffhunk://#diff-45e88b27cc58ea15345a9f1736ad4d77b8f8ccf5eaa3fa0c85572876cad76a81R15-R74) [[2]](diffhunk://#diff-45e88b27cc58ea15345a9f1736ad4d77b8f8ccf5eaa3fa0c85572876cad76a81R88-R92)

### Provider Updates:

* [`src/client/gui/lib/providers.dart`](diffhunk://#diff-62ce57ce08e2a6bf574b13c2d0798b8e626d66bcbdbc89e7f19c49a530d42fd2L20-R29): Added a new provider, `ffiAvailableProvider`, to propagate the FFI availability status throughout the application. Updated `grpcClientProvider` and `daemonAvailableProvider` to incorporate FFI availability checks, ensuring dependent functionality behaves appropriately when the FFI library is unavailable. [[1]](diffhunk://#diff-62ce57ce08e2a6bf574b13c2d0798b8e626d66bcbdbc89e7f19c49a530d42fd2L20-R29) [[2]](diffhunk://#diff-62ce57ce08e2a6bf574b13c2d0798b8e626d66bcbdbc89e7f19c49a530d42fd2R73-R77)

### CODE REVIEW

File: src/client/gui/lib/daemon_unavailable.dart [hunk 1]
```diff
@@ -9,24 +12,84 @@ class DaemonUnavailable extends ConsumerWidget {
...
+          CircularProgressIndicator(color: Colors.orange),
+          SizedBox(width: 20),
+          Text('Waiting for daemon...'),
+        ]),
+      );
+    }
 
     return IgnorePointer(
-      ignoring: available,
+      ignoring:
```
Comment (sharder996) [inline src/client/gui/lib/daemon_unavailable.dart]: Do you mean to no longer have `available` here?

**Review by sharder996 — CHANGES_REQUESTED** [review]
I'm trusting you with the finer points of engineering Dart code, I'm wondering if it's possible to make the text selectable/copyable?

**Comment by sharder996** [comment]
You can't make the text selectable? @levkropp

**Comment by levkropp** [comment]
I added a button to copy the entire error to the clipboard. It seems more in line with how we do copying in multipass i.e with CopyableText (click to copy) and is faster for getting the error, but I have no strong feelings about it being just a SelectableText since this is a debug dialog.

**Comment by xmkg** [comment]
Tested in a local copy, the error message is being displayed when the libdart_ffi.so is absent in the library search path:

image

Also, the message has a nice copy button, and it works:

```
Exception: Failed to load libdart_ffi library: Invalid argument(s): Failed to load dynamic library 'libdart_ffi.so': libdart_ffi.so: cannot open shared object file: No such file or directory
```

The `Exit application` button also works.

The message disappears when I start the GUI with LD_LIBRARY_PATH: `LD_LIBRARY_PATH=./build/lib ./build/bin/multipass.gui`. Looks good to me, functionality-wise, will skim through the code with my non-existent Flutter knowledge :)
